//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AuctionListing {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AuctionListing() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.AuctionListing", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept Offers.
        /// </summary>
        internal static string AcceptOffers {
            get {
                return ResourceManager.GetString("AcceptOffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not currently authorized to bid or purchase.
        /// </summary>
        internal static string ActingUserIsNotAuthorized {
            get {
                return ResourceManager.GetString("ActingUserIsNotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your bid has been submitted..
        /// </summary>
        internal static string ActionSuccess {
            get {
                return ResourceManager.GetString("ActionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auction.
        /// </summary>
        internal static string Auction {
            get {
                return ResourceManager.GetString("Auction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A {0} up to {1} will be applied to your account..
        /// </summary>
        internal static string A_BuyerFeeDescr_UpTo_Xdollars_WillBeAppliedToYourAccount {
            get {
                return ResourceManager.GetString("A_BuyerFeeDescr_UpTo_Xdollars_WillBeAppliedToYourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A {0} up to {1} will be applied to your total..
        /// </summary>
        internal static string A_BuyerFeeDescr_UpTo_Xdollars_WillBeAppliedToYourTotal {
            get {
                return ResourceManager.GetString("A_BuyerFeeDescr_UpTo_Xdollars_WillBeAppliedToYourTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A {0} {1} will be applied to your account..
        /// </summary>
        internal static string A_Xdollars_BuyerFeeDescr_WillBeAppliedToYourAccount {
            get {
                return ResourceManager.GetString("A_Xdollars_BuyerFeeDescr_WillBeAppliedToYourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A {0} {1} will be applied to your total..
        /// </summary>
        internal static string A_Xdollars_BuyerFeeDescr_WillBeAppliedToYourTotal {
            get {
                return ResourceManager.GetString("A_Xdollars_BuyerFeeDescr_WillBeAppliedToYourTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A {0} {1} of {2} will be applied to your account..
        /// </summary>
        internal static string A_Xpct_BuyerFeeDescr_Of_Ydollars_WillBeAppliedToYourAccount {
            get {
                return ResourceManager.GetString("A_Xpct_BuyerFeeDescr_Of_Ydollars_WillBeAppliedToYourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A {0} {1} of {2} will be applied to your total..
        /// </summary>
        internal static string A_Xpct_BuyerFeeDescr_Of_Ydollars_WillBeAppliedToYourTotal {
            get {
                return ResourceManager.GetString("A_Xpct_BuyerFeeDescr_Of_Ydollars_WillBeAppliedToYourTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A {0} {1} up to {2} will be applied to your account..
        /// </summary>
        internal static string A_Xpct_BuyerFeeDescr_UpTo_Ydollars_WillBeAppliedToYourAccount {
            get {
                return ResourceManager.GetString("A_Xpct_BuyerFeeDescr_UpTo_Ydollars_WillBeAppliedToYourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A {0} {1} up to {2} will be applied to your total..
        /// </summary>
        internal static string A_Xpct_BuyerFeeDescr_UpTo_Ydollars_WillBeAppliedToYourTotal {
            get {
                return ResourceManager.GetString("A_Xpct_BuyerFeeDescr_UpTo_Ydollars_WillBeAppliedToYourTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bid Amount must be a decimal value..
        /// </summary>
        internal static string BadListingActionValue {
            get {
                return ResourceManager.GetString("BadListingActionValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bid.
        /// </summary>
        internal static string Bid {
            get {
                return ResourceManager.GetString("Bid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bid Amount is too low.
        /// </summary>
        internal static string BidAmountTooLow {
            get {
                return ResourceManager.GetString("BidAmountTooLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Bidder is the Owner.
        /// </summary>
        internal static string BidderIsOwner {
            get {
                return ResourceManager.GetString("BidderIsOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your bid is a contract between you and the listing creator.  If you have the highest bid you will enter into a legally binding purchase contract..
        /// </summary>
        internal static string BidDisclaimer {
            get {
                return ResourceManager.GetString("BidDisclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bid History.
        /// </summary>
        internal static string BidHistory {
            get {
                return ResourceManager.GetString("BidHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bid Now.
        /// </summary>
        internal static string BidNow {
            get {
                return ResourceManager.GetString("BidNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bid(s).
        /// </summary>
        internal static string Bids {
            get {
                return ResourceManager.GetString("Bids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The winning bidder will incur a Buyer Fee of.
        /// </summary>
        internal static string BuyerFeeNotice {
            get {
                return ResourceManager.GetString("BuyerFeeNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy Now.
        /// </summary>
        internal static string BuyItNow {
            get {
                return ResourceManager.GetString("BuyItNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy Now Price.
        /// </summary>
        internal static string BuyItNowPrice {
            get {
                return ResourceManager.GetString("BuyItNowPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span class=&quot;text-primary&quot;&gt;Available for immediate purchase.&lt;/span&gt;.
        /// </summary>
        internal static string BuyNowAvailable {
            get {
                return ResourceManager.GetString("BuyNowAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy Now Price.
        /// </summary>
        internal static string BuyNowPrice {
            get {
                return ResourceManager.GetString("BuyNowPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not allowed to lower your maximum bid..
        /// </summary>
        internal static string CantLowerProxyBid {
            get {
                return ResourceManager.GetString("CantLowerProxyBid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bidding has ended on this item..
        /// </summary>
        internal static string ClosedMessage {
            get {
                return ResourceManager.GetString("ClosedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm your bid of {0}..
        /// </summary>
        internal static string ConfirmBid {
            get {
                return ResourceManager.GetString("ConfirmBid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm &quot;Buy Now&quot; of {0}..
        /// </summary>
        internal static string ConfirmBuyItNow {
            get {
                return ResourceManager.GetString("ConfirmBuyItNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Bid Amount.
        /// </summary>
        internal static string ConfirmListingActionAmount {
            get {
                return ResourceManager.GetString("ConfirmListingActionAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Bid.
        /// </summary>
        internal static string CurrentBid {
            get {
                return ResourceManager.GetString("CurrentBid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Price.
        /// </summary>
        internal static string CurrentPrice {
            get {
                return ResourceManager.GetString("CurrentPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Current Reserve: {0}).
        /// </summary>
        internal static string CurrentReserveX {
            get {
                return ResourceManager.GetString("CurrentReserveX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are the current high bidder, but the reserve price has not been met..
        /// </summary>
        internal static string CURRENT_HIGH_BIDDER_RESERVE_NOT_MET {
            get {
                return ResourceManager.GetString("CURRENT_HIGH_BIDDER_RESERVE_NOT_MET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic Proxy Bids may be placed days or hours before the auction ends. If two bidders bid the same amount, the earlier Proxy Bid always wins over the more recent bid..
        /// </summary>
        internal static string EarliestBidWinsNote {
            get {
                return ResourceManager.GetString("EarliestBidWinsNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item ended with accepted offer.
        /// </summary>
        internal static string ENDED_WITH_OFFER_ACCEPTED {
            get {
                return ResourceManager.GetString("ENDED_WITH_OFFER_ACCEPTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string EndsIn {
            get {
                return ResourceManager.GetString("EndsIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Your Bid.
        /// </summary>
        internal static string EnterYourBid {
            get {
                return ResourceManager.GetString("EnterYourBid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Your Maximum Proxy Bid.
        /// </summary>
        internal static string EnterYourMaxBid {
            get {
                return ResourceManager.GetString("EnterYourMaxBid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extended.
        /// </summary>
        internal static string Extended {
            get {
                return ResourceManager.GetString("Extended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback Score.
        /// </summary>
        internal static string FeedbackScore {
            get {
                return ResourceManager.GetString("FeedbackScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final Bid.
        /// </summary>
        internal static string FinalBid {
            get {
                return ResourceManager.GetString("FinalBid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Seller Final Fee is a percentage of the Sale Price, charged only when a sale occurs..
        /// </summary>
        internal static string FinalFeeDescriptionNoTiers {
            get {
                return ResourceManager.GetString("FinalFeeDescriptionNoTiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Seller Final Fee is a percentage of the Sale Price, charged only when a sale occurs....
        /// </summary>
        internal static string FinalFeeDescriptionWithTiers {
            get {
                return ResourceManager.GetString("FinalFeeDescriptionWithTiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final Price.
        /// </summary>
        internal static string FinalPrice {
            get {
                return ResourceManager.GetString("FinalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final Price: {0}.
        /// </summary>
        internal static string FinalPriceX {
            get {
                return ResourceManager.GetString("FinalPriceX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winning Bid: {0}.
        /// </summary>
        internal static string FinalPriceXSuccessful {
            get {
                return ResourceManager.GetString("FinalPriceXSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final Bid Price: {0}.
        /// </summary>
        internal static string FinalPriceXUnsuccessful {
            get {
                return ResourceManager.GetString("FinalPriceXUnsuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed Price.
        /// </summary>
        internal static string FixedPrice {
            get {
                return ResourceManager.GetString("FixedPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Bidder.
        /// </summary>
        internal static string HighBidder {
            get {
                return ResourceManager.GetString("HighBidder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Bidder: {0}.
        /// </summary>
        internal static string HighBidderX {
            get {
                return ResourceManager.GetString("HighBidderX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bid History.
        /// </summary>
        internal static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You increased your maximum bid.
        /// </summary>
        internal static string IncreasedOwnMaxBid {
            get {
                return ResourceManager.GetString("IncreasedOwnMaxBid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This item is taxable.
        /// </summary>
        internal static string IsTaxable {
            get {
                return ResourceManager.GetString("IsTaxable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This listing changed during processing.
        /// </summary>
        internal static string ListingChangedDuringProcessing {
            get {
                return ResourceManager.GetString("ListingChangedDuringProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        internal static string ListingEndDateTime {
            get {
                return ResourceManager.GetString("ListingEndDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string ListingLocation {
            get {
                return ResourceManager.GetString("ListingLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Listing is Not Active.
        /// </summary>
        internal static string ListingNotActive {
            get {
                return ResourceManager.GetString("ListingNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Views.
        /// </summary>
        internal static string ListingPageViews {
            get {
                return ResourceManager.GetString("ListingPageViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        internal static string ListingStartedDateTime {
            get {
                return ResourceManager.GetString("ListingStartedDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        internal static string ListingStartsDateTime {
            get {
                return ResourceManager.GetString("ListingStartsDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This listing will not start until insertion fees are paid..
        /// </summary>
        internal static string LISTING_AWAITING_PAYMENT {
            get {
                return ResourceManager.GetString("LISTING_AWAITING_PAYMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This listing was deleted..
        /// </summary>
        internal static string LISTING_DELETED {
            get {
                return ResourceManager.GetString("LISTING_DELETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This listing has not started..
        /// </summary>
        internal static string LISTING_NOT_STARTED {
            get {
                return ResourceManager.GetString("LISTING_NOT_STARTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In &amp;amp; View Bid History.
        /// </summary>
        internal static string LoginViewHistory {
            get {
                return ResourceManager.GetString("LoginViewHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not the high bidder.  You can increase your bid at any time..
        /// </summary>
        internal static string LOSING {
            get {
                return ResourceManager.GetString("LOSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You did not win this item..
        /// </summary>
        internal static string LOST {
            get {
                return ResourceManager.GetString("LOST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOST.
        /// </summary>
        internal static string Lost_Concise {
            get {
                return ResourceManager.GetString("Lost_Concise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reserve price was not met.  You did not win this item..
        /// </summary>
        internal static string LOST_RESERVE_NOT_MET {
            get {
                return ResourceManager.GetString("LOST_RESERVE_NOT_MET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lower Reserve Price.
        /// </summary>
        internal static string LowerReservePrice {
            get {
                return ResourceManager.GetString("LowerReservePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecting this option will decrease the Reserve Price to the current minimum bid amount, ensuring that the next bid will meet the Reserve..
        /// </summary>
        internal static string LowerReservePrice_Help {
            get {
                return ResourceManager.GetString("LowerReservePrice_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make Offer.
        /// </summary>
        internal static string MakeOffer {
            get {
                return ResourceManager.GetString("MakeOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Bid.
        /// </summary>
        internal static string MaxBid {
            get {
                return ResourceManager.GetString("MaxBid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Bid.
        /// </summary>
        internal static string MinimumBid {
            get {
                return ResourceManager.GetString("MinimumBid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Max Bid.
        /// </summary>
        internal static string myMaxBid {
            get {
                return ResourceManager.GetString("myMaxBid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Bid Meets Reserve?.
        /// </summary>
        internal static string NextBidMeetsReserve {
            get {
                return ResourceManager.GetString("NextBidMeetsReserve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span class=&quot;text-success&quot;&gt;No Reserve &lt;/span&gt;.
        /// </summary>
        internal static string NoReserve {
            get {
                return ResourceManager.GetString("NoReserve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This item did not sell..
        /// </summary>
        internal static string NOSALE {
            get {
                return ResourceManager.GetString("NOSALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are NOT currently winning this item!.
        /// </summary>
        internal static string NOTCURRENTLISTINGACTIONUSER {
            get {
                return ResourceManager.GetString("NOTCURRENTLISTINGACTIONUSER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOT WINNING.
        /// </summary>
        internal static string NotWinning_Concise {
            get {
                return ResourceManager.GetString("NotWinning_Concise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have any activity with this item..
        /// </summary>
        internal static string NO_ACTIVITY {
            get {
                return ResourceManager.GetString("NO_ACTIVITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not bid on this item..
        /// </summary>
        internal static string NO_ACTIVITY_AS_BUYER {
            get {
                return ResourceManager.GetString("NO_ACTIVITY_AS_BUYER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This item does not have any bid activity..
        /// </summary>
        internal static string NO_ACTIVITY_AS_SELLER {
            get {
                return ResourceManager.GetString("NO_ACTIVITY_AS_SELLER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer Message.
        /// </summary>
        internal static string OfferMessage {
            get {
                return ResourceManager.GetString("OfferMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        internal static string Owner {
            get {
                return ResourceManager.GetString("Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select your intended bid amount:.
        /// </summary>
        internal static string PleaseSelectTheAmountYouIntendedToEnter {
            get {
                return ResourceManager.GetString("PleaseSelectTheAmountYouIntendedToEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Post Listing Fee is based on the Starting Bid....
        /// </summary>
        internal static string PostListingFeeIsBasedOnXxx {
            get {
                return ResourceManager.GetString("PostListingFeeIsBasedOnXxx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price including {0}: up to {1}.
        /// </summary>
        internal static string PriceIncluding_BuyerFeeDescr_UpTo_Xdollars {
            get {
                return ResourceManager.GetString("PriceIncluding_BuyerFeeDescr_UpTo_Xdollars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price including {0}: {1}.
        /// </summary>
        internal static string PriceIncluding_BuyerFeeDescr_Xdollars {
            get {
                return ResourceManager.GetString("PriceIncluding_BuyerFeeDescr_Xdollars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Bid Increased.
        /// </summary>
        internal static string ProxyAmountIncreased {
            get {
                return ResourceManager.GetString("ProxyAmountIncreased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been outbid by proxy..
        /// </summary>
        internal static string ProxyBeatingNewBid {
            get {
                return ResourceManager.GetString("ProxyBeatingNewBid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy Bid.
        /// </summary>
        internal static string ProxyBid {
            get {
                return ResourceManager.GetString("ProxyBid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} will bid incrementally for you up to your maximum bid. Your maximum bid is kept a secret from other users..
        /// </summary>
        internal static string ProxyBidDisclaimer {
            get {
                return ResourceManager.GetString("ProxyBidDisclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occasionally you&apos;ll see bids increase by less than the bid increment. This means that someone else placed a bid just slightly higher than your Automatic Proxy Bid amount..
        /// </summary>
        internal static string ProxyBidIncrementNote {
            get {
                return ResourceManager.GetString("ProxyBidIncrementNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Bid {0}.
        /// </summary>
        internal static string QuickBid {
            get {
                return ResourceManager.GetString("QuickBid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span class=&quot;text-success&quot;&gt;Reserve Price Met&lt;/span&gt;.
        /// </summary>
        internal static string ReserveMet {
            get {
                return ResourceManager.GetString("ReserveMet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span class=&quot;text-danger&quot;&gt;Reserve Price Not Met&lt;/span&gt;.
        /// </summary>
        internal static string ReserveNotMet {
            get {
                return ResourceManager.GetString("ReserveNotMet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserve Price.
        /// </summary>
        internal static string ReservePrice {
            get {
                return ResourceManager.GetString("ReservePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This item has bids, however the reserve has not been met..
        /// </summary>
        internal static string RESERVE_NOT_MET {
            get {
                return ResourceManager.GetString("RESERVE_NOT_MET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This item has bids, however the reserve has not been met..
        /// </summary>
        internal static string RESERVE_NOT_MET_AS_SELLER {
            get {
                return ResourceManager.GetString("RESERVE_NOT_MET_AS_SELLER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review and Confirm Offer.
        /// </summary>
        internal static string ReviewAndConfirmOffer {
            get {
                return ResourceManager.GetString("ReviewAndConfirmOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Offer.
        /// </summary>
        internal static string ReviewOffer {
            get {
                return ResourceManager.GetString("ReviewOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts In.
        /// </summary>
        internal static string ScheduledListingStartsIn {
            get {
                return ResourceManager.GetString("ScheduledListingStartsIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bidding on this listing starts on {0}.
        /// </summary>
        internal static string ScheduledListingStartsOnX {
            get {
                return ResourceManager.GetString("ScheduledListingStartsOnX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About The Seller.
        /// </summary>
        internal static string SellerDetailsTitle {
            get {
                return ResourceManager.GetString("SellerDetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listed By.
        /// </summary>
        internal static string SellerUsername {
            get {
                return ResourceManager.GetString("SellerUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This item sold!.
        /// </summary>
        internal static string SOLD {
            get {
                return ResourceManager.GetString("SOLD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Bid.
        /// </summary>
        internal static string StartingBid {
            get {
                return ResourceManager.GetString("StartingBid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Bid.
        /// </summary>
        internal static string StartingBidPrice {
            get {
                return ResourceManager.GetString("StartingBidPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Bid: {0}.
        /// </summary>
        internal static string StartingBidX {
            get {
                return ResourceManager.GetString("StartingBidX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Bid.
        /// </summary>
        internal static string SubmitBid {
            get {
                return ResourceManager.GetString("SubmitBid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Auction Listing.
        /// </summary>
        internal static string TypeIconAlt {
            get {
                return ResourceManager.GetString("TypeIconAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNKNOWN.
        /// </summary>
        internal static string UNKNOWN {
            get {
                return ResourceManager.GetString("UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watching.
        /// </summary>
        internal static string UsersWatching {
            get {
                return ResourceManager.GetString("UsersWatching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Details.
        /// </summary>
        internal static string ViewDetails {
            get {
                return ResourceManager.GetString("ViewDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Bid History.
        /// </summary>
        internal static string ViewHistory {
            get {
                return ResourceManager.GetString("ViewHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Seller&apos;s Other Listings.
        /// </summary>
        internal static string ViewSellersOtherListings {
            get {
                return ResourceManager.GetString("ViewSellersOtherListings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are currently winning this item!.
        /// </summary>
        internal static string WINNING {
            get {
                return ResourceManager.GetString("WINNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WINNING.
        /// </summary>
        internal static string Winning_Concise {
            get {
                return ResourceManager.GetString("Winning_Concise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have won this item!.
        /// </summary>
        internal static string WON {
            get {
                return ResourceManager.GetString("WON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WON.
        /// </summary>
        internal static string Won_Concise {
            get {
                return ResourceManager.GetString("Won_Concise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A bidder is winning this item!.
        /// </summary>
        internal static string WOULD_SELL {
            get {
                return ResourceManager.GetString("WOULD_SELL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Bid(s).
        /// </summary>
        internal static string XBids {
            get {
                return ResourceManager.GetString("XBids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Bid.
        /// </summary>
        internal static string YourBid {
            get {
                return ResourceManager.GetString("YourBid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Last Bid Was.
        /// </summary>
        internal static string YourLastBidWas {
            get {
                return ResourceManager.GetString("YourLastBidWas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Maximum Bid Is.
        /// </summary>
        internal static string YourMaximumBidIs {
            get {
                return ResourceManager.GetString("YourMaximumBidIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Maximum Proxy Bid.
        /// </summary>
        internal static string YourMaximumProxyBid {
            get {
                return ResourceManager.GetString("YourMaximumProxyBid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Offer.
        /// </summary>
        internal static string YourOffer {
            get {
                return ResourceManager.GetString("YourOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your offer was accepted.
        /// </summary>
        internal static string YOUR_OFFER_ACCEPTED {
            get {
                return ResourceManager.GetString("YOUR_OFFER_ACCEPTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your offer was declined.
        /// </summary>
        internal static string YOUR_OFFER_DECLINED {
            get {
                return ResourceManager.GetString("YOUR_OFFER_DECLINED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have an offer awaiting your response.
        /// </summary>
        internal static string YOU_HAVE_PENDING_OFFER {
            get {
                return ResourceManager.GetString("YOU_HAVE_PENDING_OFFER", resourceCulture);
            }
        }
    }
}
