//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ClassifiedListing {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ClassifiedListing() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ClassifiedListing", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not currently authorized to contact the listing owner.
        /// </summary>
        internal static string ActingUserIsNotAuthorized {
            get {
                return ResourceManager.GetString("ActingUserIsNotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Message Has Been Sent..
        /// </summary>
        internal static string ActionSuccess {
            get {
                return ResourceManager.GetString("ActionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [not logged in yet].
        /// </summary>
        internal static string AnonymousUser {
            get {
                return ResourceManager.GetString("AnonymousUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asking Price.
        /// </summary>
        internal static string AskingPrice {
            get {
                return ResourceManager.GetString("AskingPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send a message or question to the listing owner:.
        /// </summary>
        internal static string ClassifiedDisclaimer {
            get {
                return ResourceManager.GetString("ClassifiedDisclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; ({1}).
        /// </summary>
        internal static string ClassifiedSubject {
            get {
                return ResourceManager.GetString("ClassifiedSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This listing has expired..
        /// </summary>
        internal static string ClosedMessage {
            get {
                return ResourceManager.GetString("ClosedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Your Message.
        /// </summary>
        internal static string ConfirmMessage {
            get {
                return ResourceManager.GetString("ConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Poster.
        /// </summary>
        internal static string ContactSeller {
            get {
                return ResourceManager.GetString("ContactSeller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback Score.
        /// </summary>
        internal static string FeedbackScore {
            get {
                return ResourceManager.GetString("FeedbackScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FinalFeeDescriptionNoTiers {
            get {
                return ResourceManager.GetString("FinalFeeDescriptionNoTiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FinalFeeDescriptionWithTiers {
            get {
                return ResourceManager.GetString("FinalFeeDescriptionWithTiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Expires.
        /// </summary>
        internal static string ListingEndDateTime {
            get {
                return ResourceManager.GetString("ListingEndDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Views.
        /// </summary>
        internal static string ListingPageViews {
            get {
                return ResourceManager.GetString("ListingPageViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Posted.
        /// </summary>
        internal static string ListingStartDateTime {
            get {
                return ResourceManager.GetString("ListingStartDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This listing will not start until insertion fees are paid..
        /// </summary>
        internal static string LISTING_AWAITING_PAYMENT {
            get {
                return ResourceManager.GetString("LISTING_AWAITING_PAYMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This listing was deleted..
        /// </summary>
        internal static string LISTING_DELETED {
            get {
                return ResourceManager.GetString("LISTING_DELETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listing owner is not accepting offers until {0}.
        /// </summary>
        internal static string LISTING_NOT_STARTED {
            get {
                return ResourceManager.GetString("LISTING_NOT_STARTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available {0}.
        /// </summary>
        internal static string LISTING_NOT_STARTED_QA {
            get {
                return ResourceManager.GetString("LISTING_NOT_STARTED_QA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string MessageBody {
            get {
                return ResourceManager.GetString("MessageBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        internal static string MessageSubject {
            get {
                return ResourceManager.GetString("MessageSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask Price.
        /// </summary>
        internal static string OriginalAskingPrice {
            get {
                return ResourceManager.GetString("OriginalAskingPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PostListingFeeIsBasedOnXxx {
            get {
                return ResourceManager.GetString("PostListingFeeIsBasedOnXxx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview For.
        /// </summary>
        internal static string PreviewUntil {
            get {
                return ResourceManager.GetString("PreviewUntil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price (Optional).
        /// </summary>
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string PurchasePrice {
            get {
                return ResourceManager.GetString("PurchasePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available In: {0}.
        /// </summary>
        internal static string ScheduledListingStartsInX {
            get {
                return ResourceManager.GetString("ScheduledListingStartsInX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available on {0}.
        /// </summary>
        internal static string ScheduledListingStartsOnX {
            get {
                return ResourceManager.GetString("ScheduledListingStartsOnX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About The Poster.
        /// </summary>
        internal static string SellerDetailsTitle {
            get {
                return ResourceManager.GetString("SellerDetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posted By.
        /// </summary>
        internal static string SellerUsername {
            get {
                return ResourceManager.GetString("SellerUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Private Message.
        /// </summary>
        internal static string SendMessage {
            get {
                return ResourceManager.GetString("SendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message from {0} regarding listing #{1}.
        /// </summary>
        internal static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Public Question.
        /// </summary>
        internal static string SubmitPublicQA {
            get {
                return ResourceManager.GetString("SubmitPublicQA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classified Ad Listing.
        /// </summary>
        internal static string TypeIconAlt {
            get {
                return ResourceManager.GetString("TypeIconAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watching.
        /// </summary>
        internal static string UsersWatching {
            get {
                return ResourceManager.GetString("UsersWatching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Ad.
        /// </summary>
        internal static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Ad.
        /// </summary>
        internal static string ViewAd {
            get {
                return ResourceManager.GetString("ViewAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View {0}&apos;s Listings.
        /// </summary>
        internal static string ViewSellersOtherListings {
            get {
                return ResourceManager.GetString("ViewSellersOtherListings", resourceCulture);
            }
        }
    }
}
