//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Countries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Countries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Countries", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AFGHANISTAN.
        /// </summary>
        internal static string AFGHANISTAN {
            get {
                return ResourceManager.GetString("AFGHANISTAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALBANIA.
        /// </summary>
        internal static string ALBANIA {
            get {
                return ResourceManager.GetString("ALBANIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALGERIA.
        /// </summary>
        internal static string ALGERIA {
            get {
                return ResourceManager.GetString("ALGERIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AMERICAN SAMOA.
        /// </summary>
        internal static string AMERICAN_SAMOA {
            get {
                return ResourceManager.GetString("AMERICAN_SAMOA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ANDORRA.
        /// </summary>
        internal static string ANDORRA {
            get {
                return ResourceManager.GetString("ANDORRA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ANGOLA.
        /// </summary>
        internal static string ANGOLA {
            get {
                return ResourceManager.GetString("ANGOLA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ANGUILLA.
        /// </summary>
        internal static string ANGUILLA {
            get {
                return ResourceManager.GetString("ANGUILLA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ANTARCTICA.
        /// </summary>
        internal static string ANTARCTICA {
            get {
                return ResourceManager.GetString("ANTARCTICA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ANTIGUA AND BARBUDA.
        /// </summary>
        internal static string ANTIGUA_AND_BARBUDA {
            get {
                return ResourceManager.GetString("ANTIGUA_AND_BARBUDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ARGENTINA.
        /// </summary>
        internal static string ARGENTINA {
            get {
                return ResourceManager.GetString("ARGENTINA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ARMENIA.
        /// </summary>
        internal static string ARMENIA {
            get {
                return ResourceManager.GetString("ARMENIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ARUBA.
        /// </summary>
        internal static string ARUBA {
            get {
                return ResourceManager.GetString("ARUBA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUSTRALIA.
        /// </summary>
        internal static string AUSTRALIA {
            get {
                return ResourceManager.GetString("AUSTRALIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUSTRIA.
        /// </summary>
        internal static string AUSTRIA {
            get {
                return ResourceManager.GetString("AUSTRIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AZERBAIJAN.
        /// </summary>
        internal static string AZERBAIJAN {
            get {
                return ResourceManager.GetString("AZERBAIJAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BAHAMAS.
        /// </summary>
        internal static string BAHAMAS {
            get {
                return ResourceManager.GetString("BAHAMAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BAHRAIN.
        /// </summary>
        internal static string BAHRAIN {
            get {
                return ResourceManager.GetString("BAHRAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BANGLADESH.
        /// </summary>
        internal static string BANGLADESH {
            get {
                return ResourceManager.GetString("BANGLADESH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BARBADOS.
        /// </summary>
        internal static string BARBADOS {
            get {
                return ResourceManager.GetString("BARBADOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BELARUS.
        /// </summary>
        internal static string BELARUS {
            get {
                return ResourceManager.GetString("BELARUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BELGIUM.
        /// </summary>
        internal static string BELGIUM {
            get {
                return ResourceManager.GetString("BELGIUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BELIZE.
        /// </summary>
        internal static string BELIZE {
            get {
                return ResourceManager.GetString("BELIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BENIN.
        /// </summary>
        internal static string BENIN {
            get {
                return ResourceManager.GetString("BENIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BERMUDA.
        /// </summary>
        internal static string BERMUDA {
            get {
                return ResourceManager.GetString("BERMUDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BHUTAN.
        /// </summary>
        internal static string BHUTAN {
            get {
                return ResourceManager.GetString("BHUTAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BOLIVIA.
        /// </summary>
        internal static string BOLIVIA {
            get {
                return ResourceManager.GetString("BOLIVIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BOSNIA AND HERZEGOVINA.
        /// </summary>
        internal static string BOSNIA_AND_HERZEGOVINA {
            get {
                return ResourceManager.GetString("BOSNIA_AND_HERZEGOVINA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BOTSWANA.
        /// </summary>
        internal static string BOTSWANA {
            get {
                return ResourceManager.GetString("BOTSWANA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BOUVET ISLAND.
        /// </summary>
        internal static string BOUVET_ISLAND {
            get {
                return ResourceManager.GetString("BOUVET_ISLAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BRAZIL.
        /// </summary>
        internal static string BRAZIL {
            get {
                return ResourceManager.GetString("BRAZIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BRITISH INDIAN OCEAN TERRITORY.
        /// </summary>
        internal static string BRITISH_INDIAN_OCEAN_TERRITORY {
            get {
                return ResourceManager.GetString("BRITISH_INDIAN_OCEAN_TERRITORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BRUNEI DARUSSALAM.
        /// </summary>
        internal static string BRUNEI_DARUSSALAM {
            get {
                return ResourceManager.GetString("BRUNEI_DARUSSALAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BULGARIA.
        /// </summary>
        internal static string BULGARIA {
            get {
                return ResourceManager.GetString("BULGARIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BURKINA FASO.
        /// </summary>
        internal static string BURKINA_FASO {
            get {
                return ResourceManager.GetString("BURKINA_FASO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BURUNDI.
        /// </summary>
        internal static string BURUNDI {
            get {
                return ResourceManager.GetString("BURUNDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAMBODIA.
        /// </summary>
        internal static string CAMBODIA {
            get {
                return ResourceManager.GetString("CAMBODIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAMEROON.
        /// </summary>
        internal static string CAMEROON {
            get {
                return ResourceManager.GetString("CAMEROON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANADA.
        /// </summary>
        internal static string CANADA {
            get {
                return ResourceManager.GetString("CANADA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAPE VERDE.
        /// </summary>
        internal static string CAPE_VERDE {
            get {
                return ResourceManager.GetString("CAPE_VERDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAYMAN ISLANDS.
        /// </summary>
        internal static string CAYMAN_ISLANDS {
            get {
                return ResourceManager.GetString("CAYMAN_ISLANDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CENTRAL AFRICAN REPUBLIC.
        /// </summary>
        internal static string CENTRAL_AFRICAN_REPUBLIC {
            get {
                return ResourceManager.GetString("CENTRAL_AFRICAN_REPUBLIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHAD.
        /// </summary>
        internal static string CHAD {
            get {
                return ResourceManager.GetString("CHAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHILE.
        /// </summary>
        internal static string CHILE {
            get {
                return ResourceManager.GetString("CHILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHINA.
        /// </summary>
        internal static string CHINA {
            get {
                return ResourceManager.GetString("CHINA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHRISTMAS ISLAND.
        /// </summary>
        internal static string CHRISTMAS_ISLAND {
            get {
                return ResourceManager.GetString("CHRISTMAS_ISLAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COCOS (KEELING) ISLANDS.
        /// </summary>
        internal static string COCOS__KEELING__ISLANDS {
            get {
                return ResourceManager.GetString("COCOS__KEELING__ISLANDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COLOMBIA.
        /// </summary>
        internal static string COLOMBIA {
            get {
                return ResourceManager.GetString("COLOMBIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMOROS.
        /// </summary>
        internal static string COMOROS {
            get {
                return ResourceManager.GetString("COMOROS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONGO.
        /// </summary>
        internal static string CONGO {
            get {
                return ResourceManager.GetString("CONGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONGO, THE DEMOCRATIC REPUBLIC OF THE.
        /// </summary>
        internal static string CONGO__THE_DEMOCRATIC_REPUBLIC_OF_THE {
            get {
                return ResourceManager.GetString("CONGO__THE_DEMOCRATIC_REPUBLIC_OF_THE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COOK ISLANDS.
        /// </summary>
        internal static string COOK_ISLANDS {
            get {
                return ResourceManager.GetString("COOK_ISLANDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COSTA RICA.
        /// </summary>
        internal static string COSTA_RICA {
            get {
                return ResourceManager.GetString("COSTA_RICA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CROATIA.
        /// </summary>
        internal static string CROATIA {
            get {
                return ResourceManager.GetString("CROATIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CUBA.
        /// </summary>
        internal static string CUBA {
            get {
                return ResourceManager.GetString("CUBA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CYPRUS.
        /// </summary>
        internal static string CYPRUS {
            get {
                return ResourceManager.GetString("CYPRUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CZECH REPUBLIC.
        /// </summary>
        internal static string CZECH_REPUBLIC {
            get {
                return ResourceManager.GetString("CZECH_REPUBLIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CÔTE D&apos;IVOIRE.
        /// </summary>
        internal static string C_TE_D_IVOIRE {
            get {
                return ResourceManager.GetString("C_TE_D_IVOIRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DENMARK.
        /// </summary>
        internal static string DENMARK {
            get {
                return ResourceManager.GetString("DENMARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DJIBOUTI.
        /// </summary>
        internal static string DJIBOUTI {
            get {
                return ResourceManager.GetString("DJIBOUTI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOMINICA.
        /// </summary>
        internal static string DOMINICA {
            get {
                return ResourceManager.GetString("DOMINICA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOMINICAN REPUBLIC.
        /// </summary>
        internal static string DOMINICAN_REPUBLIC {
            get {
                return ResourceManager.GetString("DOMINICAN_REPUBLIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ECUADOR.
        /// </summary>
        internal static string ECUADOR {
            get {
                return ResourceManager.GetString("ECUADOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EGYPT.
        /// </summary>
        internal static string EGYPT {
            get {
                return ResourceManager.GetString("EGYPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EL SALVADOR.
        /// </summary>
        internal static string EL_SALVADOR {
            get {
                return ResourceManager.GetString("EL_SALVADOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EQUATORIAL GUINEA.
        /// </summary>
        internal static string EQUATORIAL_GUINEA {
            get {
                return ResourceManager.GetString("EQUATORIAL_GUINEA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERITREA.
        /// </summary>
        internal static string ERITREA {
            get {
                return ResourceManager.GetString("ERITREA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESTONIA.
        /// </summary>
        internal static string ESTONIA {
            get {
                return ResourceManager.GetString("ESTONIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ETHIOPIA.
        /// </summary>
        internal static string ETHIOPIA {
            get {
                return ResourceManager.GetString("ETHIOPIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FALKLAND ISLANDS (MALVINAS).
        /// </summary>
        internal static string FALKLAND_ISLANDS__MALVINAS_ {
            get {
                return ResourceManager.GetString("FALKLAND_ISLANDS__MALVINAS_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAROE ISLANDS.
        /// </summary>
        internal static string FAROE_ISLANDS {
            get {
                return ResourceManager.GetString("FAROE_ISLANDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIJI.
        /// </summary>
        internal static string FIJI {
            get {
                return ResourceManager.GetString("FIJI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FINLAND.
        /// </summary>
        internal static string FINLAND {
            get {
                return ResourceManager.GetString("FINLAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FRANCE.
        /// </summary>
        internal static string FRANCE {
            get {
                return ResourceManager.GetString("FRANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FRENCH GUIANA.
        /// </summary>
        internal static string FRENCH_GUIANA {
            get {
                return ResourceManager.GetString("FRENCH_GUIANA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FRENCH POLYNESIA.
        /// </summary>
        internal static string FRENCH_POLYNESIA {
            get {
                return ResourceManager.GetString("FRENCH_POLYNESIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FRENCH SOUTHERN TERRITORIES.
        /// </summary>
        internal static string FRENCH_SOUTHERN_TERRITORIES {
            get {
                return ResourceManager.GetString("FRENCH_SOUTHERN_TERRITORIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GABON.
        /// </summary>
        internal static string GABON {
            get {
                return ResourceManager.GetString("GABON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GAMBIA.
        /// </summary>
        internal static string GAMBIA {
            get {
                return ResourceManager.GetString("GAMBIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GEORGIA.
        /// </summary>
        internal static string GEORGIA {
            get {
                return ResourceManager.GetString("GEORGIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GERMANY.
        /// </summary>
        internal static string GERMANY {
            get {
                return ResourceManager.GetString("GERMANY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GHANA.
        /// </summary>
        internal static string GHANA {
            get {
                return ResourceManager.GetString("GHANA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GIBRALTAR.
        /// </summary>
        internal static string GIBRALTAR {
            get {
                return ResourceManager.GetString("GIBRALTAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GREECE.
        /// </summary>
        internal static string GREECE {
            get {
                return ResourceManager.GetString("GREECE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GREENLAND.
        /// </summary>
        internal static string GREENLAND {
            get {
                return ResourceManager.GetString("GREENLAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GRENADA.
        /// </summary>
        internal static string GRENADA {
            get {
                return ResourceManager.GetString("GRENADA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GUADELOUPE.
        /// </summary>
        internal static string GUADELOUPE {
            get {
                return ResourceManager.GetString("GUADELOUPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GUAM.
        /// </summary>
        internal static string GUAM {
            get {
                return ResourceManager.GetString("GUAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GUATEMALA.
        /// </summary>
        internal static string GUATEMALA {
            get {
                return ResourceManager.GetString("GUATEMALA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GUERNSEY.
        /// </summary>
        internal static string GUERNSEY {
            get {
                return ResourceManager.GetString("GUERNSEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GUINEA.
        /// </summary>
        internal static string GUINEA {
            get {
                return ResourceManager.GetString("GUINEA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GUINEA-BISSAU.
        /// </summary>
        internal static string GUINEA_BISSAU {
            get {
                return ResourceManager.GetString("GUINEA_BISSAU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GUYANA.
        /// </summary>
        internal static string GUYANA {
            get {
                return ResourceManager.GetString("GUYANA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HAITI.
        /// </summary>
        internal static string HAITI {
            get {
                return ResourceManager.GetString("HAITI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HEARD ISLAND AND MCDONALD ISLANDS.
        /// </summary>
        internal static string HEARD_ISLAND_AND_MCDONALD_ISLANDS {
            get {
                return ResourceManager.GetString("HEARD_ISLAND_AND_MCDONALD_ISLANDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOLY SEE (VATICAN CITY STATE).
        /// </summary>
        internal static string HOLY_SEE__VATICAN_CITY_STATE_ {
            get {
                return ResourceManager.GetString("HOLY_SEE__VATICAN_CITY_STATE_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HONDURAS.
        /// </summary>
        internal static string HONDURAS {
            get {
                return ResourceManager.GetString("HONDURAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HONG KONG.
        /// </summary>
        internal static string HONG_KONG {
            get {
                return ResourceManager.GetString("HONG_KONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HUNGARY.
        /// </summary>
        internal static string HUNGARY {
            get {
                return ResourceManager.GetString("HUNGARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ICELAND.
        /// </summary>
        internal static string ICELAND {
            get {
                return ResourceManager.GetString("ICELAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INDIA.
        /// </summary>
        internal static string INDIA {
            get {
                return ResourceManager.GetString("INDIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INDONESIA.
        /// </summary>
        internal static string INDONESIA {
            get {
                return ResourceManager.GetString("INDONESIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IRAN, ISLAMIC REPUBLIC OF.
        /// </summary>
        internal static string IRAN__ISLAMIC_REPUBLIC_OF {
            get {
                return ResourceManager.GetString("IRAN__ISLAMIC_REPUBLIC_OF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IRAQ.
        /// </summary>
        internal static string IRAQ {
            get {
                return ResourceManager.GetString("IRAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IRELAND.
        /// </summary>
        internal static string IRELAND {
            get {
                return ResourceManager.GetString("IRELAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISLE OF MAN.
        /// </summary>
        internal static string ISLE_OF_MAN {
            get {
                return ResourceManager.GetString("ISLE_OF_MAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISRAEL.
        /// </summary>
        internal static string ISRAEL {
            get {
                return ResourceManager.GetString("ISRAEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ITALY.
        /// </summary>
        internal static string ITALY {
            get {
                return ResourceManager.GetString("ITALY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JAMAICA.
        /// </summary>
        internal static string JAMAICA {
            get {
                return ResourceManager.GetString("JAMAICA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JAPAN.
        /// </summary>
        internal static string JAPAN {
            get {
                return ResourceManager.GetString("JAPAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JERSEY.
        /// </summary>
        internal static string JERSEY {
            get {
                return ResourceManager.GetString("JERSEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JORDAN.
        /// </summary>
        internal static string JORDAN {
            get {
                return ResourceManager.GetString("JORDAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KAZAKHSTAN.
        /// </summary>
        internal static string KAZAKHSTAN {
            get {
                return ResourceManager.GetString("KAZAKHSTAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KENYA.
        /// </summary>
        internal static string KENYA {
            get {
                return ResourceManager.GetString("KENYA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KIRIBATI.
        /// </summary>
        internal static string KIRIBATI {
            get {
                return ResourceManager.GetString("KIRIBATI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KOREA, DEMOCRATIC PEOPLE&apos;S REPUBLIC OF.
        /// </summary>
        internal static string KOREA__DEMOCRATIC_PEOPLE_S_REPUBLIC_OF {
            get {
                return ResourceManager.GetString("KOREA__DEMOCRATIC_PEOPLE_S_REPUBLIC_OF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KOREA, REPUBLIC OF.
        /// </summary>
        internal static string KOREA__REPUBLIC_OF {
            get {
                return ResourceManager.GetString("KOREA__REPUBLIC_OF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KUWAIT.
        /// </summary>
        internal static string KUWAIT {
            get {
                return ResourceManager.GetString("KUWAIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KYRGYZSTAN.
        /// </summary>
        internal static string KYRGYZSTAN {
            get {
                return ResourceManager.GetString("KYRGYZSTAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LAO PEOPLE&apos;S DEMOCRATIC REPUBLIC.
        /// </summary>
        internal static string LAO_PEOPLE_S_DEMOCRATIC_REPUBLIC {
            get {
                return ResourceManager.GetString("LAO_PEOPLE_S_DEMOCRATIC_REPUBLIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LATVIA.
        /// </summary>
        internal static string LATVIA {
            get {
                return ResourceManager.GetString("LATVIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEBANON.
        /// </summary>
        internal static string LEBANON {
            get {
                return ResourceManager.GetString("LEBANON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LESOTHO.
        /// </summary>
        internal static string LESOTHO {
            get {
                return ResourceManager.GetString("LESOTHO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LIBERIA.
        /// </summary>
        internal static string LIBERIA {
            get {
                return ResourceManager.GetString("LIBERIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LIBYAN ARAB JAMAHIRIYA.
        /// </summary>
        internal static string LIBYAN_ARAB_JAMAHIRIYA {
            get {
                return ResourceManager.GetString("LIBYAN_ARAB_JAMAHIRIYA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LIECHTENSTEIN.
        /// </summary>
        internal static string LIECHTENSTEIN {
            get {
                return ResourceManager.GetString("LIECHTENSTEIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LITHUANIA.
        /// </summary>
        internal static string LITHUANIA {
            get {
                return ResourceManager.GetString("LITHUANIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LUXEMBOURG.
        /// </summary>
        internal static string LUXEMBOURG {
            get {
                return ResourceManager.GetString("LUXEMBOURG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MACAO.
        /// </summary>
        internal static string MACAO {
            get {
                return ResourceManager.GetString("MACAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF.
        /// </summary>
        internal static string MACEDONIA__THE_FORMER_YUGOSLAV_REPUBLIC_OF {
            get {
                return ResourceManager.GetString("MACEDONIA__THE_FORMER_YUGOSLAV_REPUBLIC_OF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MADAGASCAR.
        /// </summary>
        internal static string MADAGASCAR {
            get {
                return ResourceManager.GetString("MADAGASCAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MALAWI.
        /// </summary>
        internal static string MALAWI {
            get {
                return ResourceManager.GetString("MALAWI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MALAYSIA.
        /// </summary>
        internal static string MALAYSIA {
            get {
                return ResourceManager.GetString("MALAYSIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MALDIVES.
        /// </summary>
        internal static string MALDIVES {
            get {
                return ResourceManager.GetString("MALDIVES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MALI.
        /// </summary>
        internal static string MALI {
            get {
                return ResourceManager.GetString("MALI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MALTA.
        /// </summary>
        internal static string MALTA {
            get {
                return ResourceManager.GetString("MALTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MARSHALL ISLANDS.
        /// </summary>
        internal static string MARSHALL_ISLANDS {
            get {
                return ResourceManager.GetString("MARSHALL_ISLANDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MARTINIQUE.
        /// </summary>
        internal static string MARTINIQUE {
            get {
                return ResourceManager.GetString("MARTINIQUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAURITANIA.
        /// </summary>
        internal static string MAURITANIA {
            get {
                return ResourceManager.GetString("MAURITANIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAURITIUS.
        /// </summary>
        internal static string MAURITIUS {
            get {
                return ResourceManager.GetString("MAURITIUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAYOTTE.
        /// </summary>
        internal static string MAYOTTE {
            get {
                return ResourceManager.GetString("MAYOTTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MEXICO.
        /// </summary>
        internal static string MEXICO {
            get {
                return ResourceManager.GetString("MEXICO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MICRONESIA, FEDERATED STATES OF.
        /// </summary>
        internal static string MICRONESIA__FEDERATED_STATES_OF {
            get {
                return ResourceManager.GetString("MICRONESIA__FEDERATED_STATES_OF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOLDOVA, REPUBLIC OF.
        /// </summary>
        internal static string MOLDOVA__REPUBLIC_OF {
            get {
                return ResourceManager.GetString("MOLDOVA__REPUBLIC_OF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MONACO.
        /// </summary>
        internal static string MONACO {
            get {
                return ResourceManager.GetString("MONACO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MONGOLIA.
        /// </summary>
        internal static string MONGOLIA {
            get {
                return ResourceManager.GetString("MONGOLIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MONTENEGRO.
        /// </summary>
        internal static string MONTENEGRO {
            get {
                return ResourceManager.GetString("MONTENEGRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MONTSERRAT.
        /// </summary>
        internal static string MONTSERRAT {
            get {
                return ResourceManager.GetString("MONTSERRAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOROCCO.
        /// </summary>
        internal static string MOROCCO {
            get {
                return ResourceManager.GetString("MOROCCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOZAMBIQUE.
        /// </summary>
        internal static string MOZAMBIQUE {
            get {
                return ResourceManager.GetString("MOZAMBIQUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MYANMAR.
        /// </summary>
        internal static string MYANMAR {
            get {
                return ResourceManager.GetString("MYANMAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAMIBIA.
        /// </summary>
        internal static string NAMIBIA {
            get {
                return ResourceManager.GetString("NAMIBIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAURU.
        /// </summary>
        internal static string NAURU {
            get {
                return ResourceManager.GetString("NAURU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEPAL.
        /// </summary>
        internal static string NEPAL {
            get {
                return ResourceManager.GetString("NEPAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NETHERLANDS.
        /// </summary>
        internal static string NETHERLANDS {
            get {
                return ResourceManager.GetString("NETHERLANDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NETHERLANDS ANTILLES.
        /// </summary>
        internal static string NETHERLANDS_ANTILLES {
            get {
                return ResourceManager.GetString("NETHERLANDS_ANTILLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEW CALEDONIA.
        /// </summary>
        internal static string NEW_CALEDONIA {
            get {
                return ResourceManager.GetString("NEW_CALEDONIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEW ZEALAND.
        /// </summary>
        internal static string NEW_ZEALAND {
            get {
                return ResourceManager.GetString("NEW_ZEALAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NICARAGUA.
        /// </summary>
        internal static string NICARAGUA {
            get {
                return ResourceManager.GetString("NICARAGUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NIGER.
        /// </summary>
        internal static string NIGER {
            get {
                return ResourceManager.GetString("NIGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NIGERIA.
        /// </summary>
        internal static string NIGERIA {
            get {
                return ResourceManager.GetString("NIGERIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NIUE.
        /// </summary>
        internal static string NIUE {
            get {
                return ResourceManager.GetString("NIUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NORFOLK ISLAND.
        /// </summary>
        internal static string NORFOLK_ISLAND {
            get {
                return ResourceManager.GetString("NORFOLK_ISLAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NORTHERN MARIANA ISLANDS.
        /// </summary>
        internal static string NORTHERN_MARIANA_ISLANDS {
            get {
                return ResourceManager.GetString("NORTHERN_MARIANA_ISLANDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NORWAY.
        /// </summary>
        internal static string NORWAY {
            get {
                return ResourceManager.GetString("NORWAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OMAN.
        /// </summary>
        internal static string OMAN {
            get {
                return ResourceManager.GetString("OMAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAKISTAN.
        /// </summary>
        internal static string PAKISTAN {
            get {
                return ResourceManager.GetString("PAKISTAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PALAU.
        /// </summary>
        internal static string PALAU {
            get {
                return ResourceManager.GetString("PALAU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PALESTINIAN TERRITORY, OCCUPIED.
        /// </summary>
        internal static string PALESTINIAN_TERRITORY__OCCUPIED {
            get {
                return ResourceManager.GetString("PALESTINIAN_TERRITORY__OCCUPIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PANAMA.
        /// </summary>
        internal static string PANAMA {
            get {
                return ResourceManager.GetString("PANAMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAPUA NEW GUINEA.
        /// </summary>
        internal static string PAPUA_NEW_GUINEA {
            get {
                return ResourceManager.GetString("PAPUA_NEW_GUINEA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PARAGUAY.
        /// </summary>
        internal static string PARAGUAY {
            get {
                return ResourceManager.GetString("PARAGUAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PERU.
        /// </summary>
        internal static string PERU {
            get {
                return ResourceManager.GetString("PERU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHILIPPINES.
        /// </summary>
        internal static string PHILIPPINES {
            get {
                return ResourceManager.GetString("PHILIPPINES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PITCAIRN.
        /// </summary>
        internal static string PITCAIRN {
            get {
                return ResourceManager.GetString("PITCAIRN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POLAND.
        /// </summary>
        internal static string POLAND {
            get {
                return ResourceManager.GetString("POLAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PORTUGAL.
        /// </summary>
        internal static string PORTUGAL {
            get {
                return ResourceManager.GetString("PORTUGAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PUERTO RICO.
        /// </summary>
        internal static string PUERTO_RICO {
            get {
                return ResourceManager.GetString("PUERTO_RICO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QATAR.
        /// </summary>
        internal static string QATAR {
            get {
                return ResourceManager.GetString("QATAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROMANIA.
        /// </summary>
        internal static string ROMANIA {
            get {
                return ResourceManager.GetString("ROMANIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RUSSIAN FEDERATION.
        /// </summary>
        internal static string RUSSIAN_FEDERATION {
            get {
                return ResourceManager.GetString("RUSSIAN_FEDERATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RWANDA.
        /// </summary>
        internal static string RWANDA {
            get {
                return ResourceManager.GetString("RWANDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RÉUNION.
        /// </summary>
        internal static string R_UNION {
            get {
                return ResourceManager.GetString("R_UNION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAINT BARTHÉLEMY.
        /// </summary>
        internal static string SAINT_BARTH_LEMY {
            get {
                return ResourceManager.GetString("SAINT_BARTH_LEMY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAINT HELENA.
        /// </summary>
        internal static string SAINT_HELENA {
            get {
                return ResourceManager.GetString("SAINT_HELENA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAINT KITTS AND NEVIS.
        /// </summary>
        internal static string SAINT_KITTS_AND_NEVIS {
            get {
                return ResourceManager.GetString("SAINT_KITTS_AND_NEVIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAINT LUCIA.
        /// </summary>
        internal static string SAINT_LUCIA {
            get {
                return ResourceManager.GetString("SAINT_LUCIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAINT MARTIN.
        /// </summary>
        internal static string SAINT_MARTIN {
            get {
                return ResourceManager.GetString("SAINT_MARTIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAINT PIERRE AND MIQUELON.
        /// </summary>
        internal static string SAINT_PIERRE_AND_MIQUELON {
            get {
                return ResourceManager.GetString("SAINT_PIERRE_AND_MIQUELON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAINT VINCENT AND THE GRENADINES.
        /// </summary>
        internal static string SAINT_VINCENT_AND_THE_GRENADINES {
            get {
                return ResourceManager.GetString("SAINT_VINCENT_AND_THE_GRENADINES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAMOA.
        /// </summary>
        internal static string SAMOA {
            get {
                return ResourceManager.GetString("SAMOA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAN MARINO.
        /// </summary>
        internal static string SAN_MARINO {
            get {
                return ResourceManager.GetString("SAN_MARINO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAO TOME AND PRINCIPE.
        /// </summary>
        internal static string SAO_TOME_AND_PRINCIPE {
            get {
                return ResourceManager.GetString("SAO_TOME_AND_PRINCIPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAUDI ARABIA.
        /// </summary>
        internal static string SAUDI_ARABIA {
            get {
                return ResourceManager.GetString("SAUDI_ARABIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SENEGAL.
        /// </summary>
        internal static string SENEGAL {
            get {
                return ResourceManager.GetString("SENEGAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SERBIA.
        /// </summary>
        internal static string SERBIA {
            get {
                return ResourceManager.GetString("SERBIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEYCHELLES.
        /// </summary>
        internal static string SEYCHELLES {
            get {
                return ResourceManager.GetString("SEYCHELLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIERRA LEONE.
        /// </summary>
        internal static string SIERRA_LEONE {
            get {
                return ResourceManager.GetString("SIERRA_LEONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SINGAPORE.
        /// </summary>
        internal static string SINGAPORE {
            get {
                return ResourceManager.GetString("SINGAPORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SLOVAKIA.
        /// </summary>
        internal static string SLOVAKIA {
            get {
                return ResourceManager.GetString("SLOVAKIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SLOVENIA.
        /// </summary>
        internal static string SLOVENIA {
            get {
                return ResourceManager.GetString("SLOVENIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOLOMON ISLANDS.
        /// </summary>
        internal static string SOLOMON_ISLANDS {
            get {
                return ResourceManager.GetString("SOLOMON_ISLANDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOMALIA.
        /// </summary>
        internal static string SOMALIA {
            get {
                return ResourceManager.GetString("SOMALIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOUTH AFRICA.
        /// </summary>
        internal static string SOUTH_AFRICA {
            get {
                return ResourceManager.GetString("SOUTH_AFRICA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS.
        /// </summary>
        internal static string SOUTH_GEORGIA_AND_THE_SOUTH_SANDWICH_ISLANDS {
            get {
                return ResourceManager.GetString("SOUTH_GEORGIA_AND_THE_SOUTH_SANDWICH_ISLANDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPAIN.
        /// </summary>
        internal static string SPAIN {
            get {
                return ResourceManager.GetString("SPAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SRI LANKA.
        /// </summary>
        internal static string SRI_LANKA {
            get {
                return ResourceManager.GetString("SRI_LANKA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUDAN.
        /// </summary>
        internal static string SUDAN {
            get {
                return ResourceManager.GetString("SUDAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SURINAME.
        /// </summary>
        internal static string SURINAME {
            get {
                return ResourceManager.GetString("SURINAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SVALBARD AND JAN MAYEN.
        /// </summary>
        internal static string SVALBARD_AND_JAN_MAYEN {
            get {
                return ResourceManager.GetString("SVALBARD_AND_JAN_MAYEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SWAZILAND.
        /// </summary>
        internal static string SWAZILAND {
            get {
                return ResourceManager.GetString("SWAZILAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SWEDEN.
        /// </summary>
        internal static string SWEDEN {
            get {
                return ResourceManager.GetString("SWEDEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SWITZERLAND.
        /// </summary>
        internal static string SWITZERLAND {
            get {
                return ResourceManager.GetString("SWITZERLAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SYRIAN ARAB REPUBLIC.
        /// </summary>
        internal static string SYRIAN_ARAB_REPUBLIC {
            get {
                return ResourceManager.GetString("SYRIAN_ARAB_REPUBLIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAIWAN, PROVINCE OF CHINA.
        /// </summary>
        internal static string TAIWAN__PROVINCE_OF_CHINA {
            get {
                return ResourceManager.GetString("TAIWAN__PROVINCE_OF_CHINA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAJIKISTAN.
        /// </summary>
        internal static string TAJIKISTAN {
            get {
                return ResourceManager.GetString("TAJIKISTAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TANZANIA, UNITED REPUBLIC OF.
        /// </summary>
        internal static string TANZANIA__UNITED_REPUBLIC_OF {
            get {
                return ResourceManager.GetString("TANZANIA__UNITED_REPUBLIC_OF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THAILAND.
        /// </summary>
        internal static string THAILAND {
            get {
                return ResourceManager.GetString("THAILAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIMOR-LESTE.
        /// </summary>
        internal static string TIMOR_LESTE {
            get {
                return ResourceManager.GetString("TIMOR_LESTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOGO.
        /// </summary>
        internal static string TOGO {
            get {
                return ResourceManager.GetString("TOGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOKELAU.
        /// </summary>
        internal static string TOKELAU {
            get {
                return ResourceManager.GetString("TOKELAU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TONGA.
        /// </summary>
        internal static string TONGA {
            get {
                return ResourceManager.GetString("TONGA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRINIDAD AND TOBAGO.
        /// </summary>
        internal static string TRINIDAD_AND_TOBAGO {
            get {
                return ResourceManager.GetString("TRINIDAD_AND_TOBAGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TUNISIA.
        /// </summary>
        internal static string TUNISIA {
            get {
                return ResourceManager.GetString("TUNISIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TURKEY.
        /// </summary>
        internal static string TURKEY {
            get {
                return ResourceManager.GetString("TURKEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TURKMENISTAN.
        /// </summary>
        internal static string TURKMENISTAN {
            get {
                return ResourceManager.GetString("TURKMENISTAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TURKS AND CAICOS ISLANDS.
        /// </summary>
        internal static string TURKS_AND_CAICOS_ISLANDS {
            get {
                return ResourceManager.GetString("TURKS_AND_CAICOS_ISLANDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TUVALU.
        /// </summary>
        internal static string TUVALU {
            get {
                return ResourceManager.GetString("TUVALU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UGANDA.
        /// </summary>
        internal static string UGANDA {
            get {
                return ResourceManager.GetString("UGANDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UKRAINE.
        /// </summary>
        internal static string UKRAINE {
            get {
                return ResourceManager.GetString("UKRAINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNITED ARAB EMIRATES.
        /// </summary>
        internal static string UNITED_ARAB_EMIRATES {
            get {
                return ResourceManager.GetString("UNITED_ARAB_EMIRATES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNITED KINGDOM.
        /// </summary>
        internal static string UNITED_KINGDOM {
            get {
                return ResourceManager.GetString("UNITED_KINGDOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNITED STATES.
        /// </summary>
        internal static string UNITED_STATES {
            get {
                return ResourceManager.GetString("UNITED_STATES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNITED STATES MINOR OUTLYING ISLANDS.
        /// </summary>
        internal static string UNITED_STATES_MINOR_OUTLYING_ISLANDS {
            get {
                return ResourceManager.GetString("UNITED_STATES_MINOR_OUTLYING_ISLANDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URUGUAY.
        /// </summary>
        internal static string URUGUAY {
            get {
                return ResourceManager.GetString("URUGUAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UZBEKISTAN.
        /// </summary>
        internal static string UZBEKISTAN {
            get {
                return ResourceManager.GetString("UZBEKISTAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VANUATU.
        /// </summary>
        internal static string VANUATU {
            get {
                return ResourceManager.GetString("VANUATU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VATICAN CITY STATE.
        /// </summary>
        internal static string VATICAN_CITY_STATE {
            get {
                return ResourceManager.GetString("VATICAN_CITY_STATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VENEZUELA.
        /// </summary>
        internal static string VENEZUELA {
            get {
                return ResourceManager.GetString("VENEZUELA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIET NAM.
        /// </summary>
        internal static string VIET_NAM {
            get {
                return ResourceManager.GetString("VIET_NAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIRGIN ISLANDS, BRITISH.
        /// </summary>
        internal static string VIRGIN_ISLANDS__BRITISH {
            get {
                return ResourceManager.GetString("VIRGIN_ISLANDS__BRITISH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIRGIN ISLANDS, U.S..
        /// </summary>
        internal static string VIRGIN_ISLANDS__U_S_ {
            get {
                return ResourceManager.GetString("VIRGIN_ISLANDS__U_S_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WALLIS AND FUTUNA.
        /// </summary>
        internal static string WALLIS_AND_FUTUNA {
            get {
                return ResourceManager.GetString("WALLIS_AND_FUTUNA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WESTERN SAHARA.
        /// </summary>
        internal static string WESTERN_SAHARA {
            get {
                return ResourceManager.GetString("WESTERN_SAHARA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YEMEN.
        /// </summary>
        internal static string YEMEN {
            get {
                return ResourceManager.GetString("YEMEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZAMBIA.
        /// </summary>
        internal static string ZAMBIA {
            get {
                return ResourceManager.GetString("ZAMBIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZIMBABWE.
        /// </summary>
        internal static string ZIMBABWE {
            get {
                return ResourceManager.GetString("ZIMBABWE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÅLAND ISLANDS.
        /// </summary>
        internal static string _LAND_ISLANDS {
            get {
                return ResourceManager.GetString("_LAND_ISLANDS", resourceCulture);
            }
        }
    }
}
