//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FixedPriceListing {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FixedPriceListing() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.FixedPriceListing", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept Offers.
        /// </summary>
        internal static string AcceptOffers {
            get {
                return ResourceManager.GetString("AcceptOffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not currently authorized purchase.
        /// </summary>
        internal static string ActingUserIsNotAuthorized {
            get {
                return ResourceManager.GetString("ActingUserIsNotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your purchase order has been submitted..
        /// </summary>
        internal static string ActionSuccess {
            get {
                return ResourceManager.GetString("ActionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available For.
        /// </summary>
        internal static string AvailableFor {
            get {
                return ResourceManager.GetString("AvailableFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available In.
        /// </summary>
        internal static string AvailableIn {
            get {
                return ResourceManager.GetString("AvailableIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A {0} {1} will be applied to your account..
        /// </summary>
        internal static string A_Xdollars_BuyerFeeDescr_WillBeAppliedToYourAccount {
            get {
                return ResourceManager.GetString("A_Xdollars_BuyerFeeDescr_WillBeAppliedToYourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A {0} {1} will be applied to your total..
        /// </summary>
        internal static string A_Xdollars_BuyerFeeDescr_WillBeAppliedToYourTotal {
            get {
                return ResourceManager.GetString("A_Xdollars_BuyerFeeDescr_WillBeAppliedToYourTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A {0} {1} of {2} will be applied to your account..
        /// </summary>
        internal static string A_Xpct_BuyerFeeDescr_Of_Ydollars_WillBeAppliedToYourAccount {
            get {
                return ResourceManager.GetString("A_Xpct_BuyerFeeDescr_Of_Ydollars_WillBeAppliedToYourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A {0} {1} of {2} will be applied to your total..
        /// </summary>
        internal static string A_Xpct_BuyerFeeDescr_Of_Ydollars_WillBeAppliedToYourTotal {
            get {
                return ResourceManager.GetString("A_Xpct_BuyerFeeDescr_Of_Ydollars_WillBeAppliedToYourTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity must be a whole number greater than zero..
        /// </summary>
        internal static string BadListingActionValue {
            get {
                return ResourceManager.GetString("BadListingActionValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Buyer is the Owner.
        /// </summary>
        internal static string BidderIsOwner {
            get {
                return ResourceManager.GetString("BidderIsOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchasing this item will incur a Buyer Fee of.
        /// </summary>
        internal static string BuyerFeeNotice {
            get {
                return ResourceManager.GetString("BuyerFeeNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not purchased this item..
        /// </summary>
        internal static string BUYER_NO_ACTIVITY {
            get {
                return ResourceManager.GetString("BUYER_NO_ACTIVITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot purchase this item.  It has sold out..
        /// </summary>
        internal static string BUYER_NO_QUANTITY_LEFT {
            get {
                return ResourceManager.GetString("BUYER_NO_QUANTITY_LEFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You previously ordered {0} of this item..
        /// </summary>
        internal static string BUYER_PURCHASED {
            get {
                return ResourceManager.GetString("BUYER_PURCHASED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy Now.
        /// </summary>
        internal static string BuyNow {
            get {
                return ResourceManager.GetString("BuyNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This item is no longer available for purchase..
        /// </summary>
        internal static string ClosedMessage {
            get {
                return ResourceManager.GetString("ClosedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm your purchase of {0} item(s) for {1} per unit..
        /// </summary>
        internal static string ConfirmPurchase {
            get {
                return ResourceManager.GetString("ConfirmPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Quantity.
        /// </summary>
        internal static string CurrentQuantity {
            get {
                return ResourceManager.GetString("CurrentQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to each.
        /// </summary>
        internal static string Each {
            get {
                return ResourceManager.GetString("Each", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item ended with accepted offer.
        /// </summary>
        internal static string ENDED_WITH_OFFER_ACCEPTED {
            get {
                return ResourceManager.GetString("ENDED_WITH_OFFER_ACCEPTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback Score.
        /// </summary>
        internal static string FeedbackScore {
            get {
                return ResourceManager.GetString("FeedbackScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Seller Final Fee is a percentage of the Sale Price, charged only when a sale occurs..
        /// </summary>
        internal static string FinalFeeDescriptionNoTiers {
            get {
                return ResourceManager.GetString("FinalFeeDescriptionNoTiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Seller Final Fee is a percentage of the Sale Price, charged only when a sale occurs....
        /// </summary>
        internal static string FinalFeeDescriptionWithTiers {
            get {
                return ResourceManager.GetString("FinalFeeDescriptionWithTiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed Price.
        /// </summary>
        internal static string FixedPrice {
            get {
                return ResourceManager.GetString("FixedPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This item is available for direct purchase from the seller.   No bidding is required.  .
        /// </summary>
        internal static string FixedPriceDisclaimer {
            get {
                return ResourceManager.GetString("FixedPriceDisclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase History.
        /// </summary>
        internal static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This item is taxable.
        /// </summary>
        internal static string IsTaxable {
            get {
                return ResourceManager.GetString("IsTaxable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listed Price: {0}.
        /// </summary>
        internal static string ListedPrice {
            get {
                return ResourceManager.GetString("ListedPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This listing changed during processing.
        /// </summary>
        internal static string ListingChangedDuringProcessing {
            get {
                return ResourceManager.GetString("ListingChangedDuringProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Until.
        /// </summary>
        internal static string ListingEndDateTime {
            get {
                return ResourceManager.GetString("ListingEndDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listing Location.
        /// </summary>
        internal static string ListingLocation {
            get {
                return ResourceManager.GetString("ListingLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listing is Not Active.
        /// </summary>
        internal static string ListingNotActive {
            get {
                return ResourceManager.GetString("ListingNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Views.
        /// </summary>
        internal static string ListingPageViews {
            get {
                return ResourceManager.GetString("ListingPageViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Since.
        /// </summary>
        internal static string ListingStartedDateTime {
            get {
                return ResourceManager.GetString("ListingStartedDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available At.
        /// </summary>
        internal static string ListingStartsDateTime {
            get {
                return ResourceManager.GetString("ListingStartsDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This listing will not start until insertion fees are paid..
        /// </summary>
        internal static string LISTING_AWAITING_PAYMENT {
            get {
                return ResourceManager.GetString("LISTING_AWAITING_PAYMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This listing was deleted..
        /// </summary>
        internal static string LISTING_DELETED {
            get {
                return ResourceManager.GetString("LISTING_DELETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This listing has not started..
        /// </summary>
        internal static string LISTING_NOT_STARTED {
            get {
                return ResourceManager.GetString("LISTING_NOT_STARTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make Offer.
        /// </summary>
        internal static string MakeOffer {
            get {
                return ResourceManager.GetString("MakeOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer Message.
        /// </summary>
        internal static string OfferMessage {
            get {
                return ResourceManager.GetString("OfferMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        internal static string Owner {
            get {
                return ResourceManager.GetString("Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Per Item.
        /// </summary>
        internal static string PerItem {
            get {
                return ResourceManager.GetString("PerItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Post Listing Fee is based on the Price....
        /// </summary>
        internal static string PostListingFeeIsBasedOnXxx {
            get {
                return ResourceManager.GetString("PostListingFeeIsBasedOnXxx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price including {0}: {1}.
        /// </summary>
        internal static string PriceIncluding_BuyerFeeDescr_Xdollars {
            get {
                return ResourceManager.GetString("PriceIncluding_BuyerFeeDescr_Xdollars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase History.
        /// </summary>
        internal static string PurchaseHistory {
            get {
                return ResourceManager.GetString("PurchaseHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Price.
        /// </summary>
        internal static string PurchasePrice {
            get {
                return ResourceManager.GetString("PurchasePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty Available.
        /// </summary>
        internal static string QtyAvailable {
            get {
                return ResourceManager.GetString("QtyAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity Available.
        /// </summary>
        internal static string QuantityAvailable {
            get {
                return ResourceManager.GetString("QuantityAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity too high.
        /// </summary>
        internal static string QuantityTooHigh {
            get {
                return ResourceManager.GetString("QuantityTooHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QTY.
        /// </summary>
        internal static string Quantity_small {
            get {
                return ResourceManager.GetString("Quantity_small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review and Confirm Offer.
        /// </summary>
        internal static string ReviewAndConfirmOffer {
            get {
                return ResourceManager.GetString("ReviewAndConfirmOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Offer.
        /// </summary>
        internal static string ReviewOffer {
            get {
                return ResourceManager.GetString("ReviewOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available In: {0}.
        /// </summary>
        internal static string ScheduledListingStartsInX {
            get {
                return ResourceManager.GetString("ScheduledListingStartsInX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available for purchase on {0}.
        /// </summary>
        internal static string ScheduledListingStartsOnX {
            get {
                return ResourceManager.GetString("ScheduledListingStartsOnX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About The Seller.
        /// </summary>
        internal static string SellerDetailsTitle {
            get {
                return ResourceManager.GetString("SellerDetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listed By.
        /// </summary>
        internal static string SellerUsername {
            get {
                return ResourceManager.GetString("SellerUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have made at least one sale..
        /// </summary>
        internal static string SELLER_ACTIVITY {
            get {
                return ResourceManager.GetString("SELLER_ACTIVITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No sales at this time..
        /// </summary>
        internal static string SELLER_NO_ACTIVITY {
            get {
                return ResourceManager.GetString("SELLER_NO_ACTIVITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have made at least one sale..
        /// </summary>
        internal static string SELLER_SUCCESSFUL {
            get {
                return ResourceManager.GetString("SELLER_SUCCESSFUL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No sales..
        /// </summary>
        internal static string SELLER_UNSUCCESSFUL {
            get {
                return ResourceManager.GetString("SELLER_UNSUCCESSFUL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy Now Listing.
        /// </summary>
        internal static string TypeIconAlt {
            get {
                return ResourceManager.GetString("TypeIconAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNKNOWN.
        /// </summary>
        internal static string UNKNOWN {
            get {
                return ResourceManager.GetString("UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watching.
        /// </summary>
        internal static string UsersWatching {
            get {
                return ResourceManager.GetString("UsersWatching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Purchase History.
        /// </summary>
        internal static string ViewPurchaseHistory {
            get {
                return ResourceManager.GetString("ViewPurchaseHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Seller&apos;s Other Listings.
        /// </summary>
        internal static string ViewSellersOtherListings {
            get {
                return ResourceManager.GetString("ViewSellersOtherListings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Unsold.
        /// </summary>
        internal static string XUnsold {
            get {
                return ResourceManager.GetString("XUnsold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Offer.
        /// </summary>
        internal static string YourOffer {
            get {
                return ResourceManager.GetString("YourOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your offer was accepted.
        /// </summary>
        internal static string YOUR_OFFER_ACCEPTED {
            get {
                return ResourceManager.GetString("YOUR_OFFER_ACCEPTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your offer was declined.
        /// </summary>
        internal static string YOUR_OFFER_DECLINED {
            get {
                return ResourceManager.GetString("YOUR_OFFER_DECLINED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have an offer awaiting your response.
        /// </summary>
        internal static string YOU_HAVE_PENDING_OFFER {
            get {
                return ResourceManager.GetString("YOU_HAVE_PENDING_OFFER", resourceCulture);
            }
        }
    }
}
