//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Licensing {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Licensing() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Licensing", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The licence server could not be contacted. Either the server does not have an active Internet connection, or a firewall is blocking communication.  Please contact RainWorx support to resolve the issue..
        /// </summary>
        internal static string CheckErrorCouldNotConnect {
            get {
                return ResourceManager.GetString("CheckErrorCouldNotConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your licence has been disabled by RainWorx.  Please contact RainWorx support to resolve the issue..
        /// </summary>
        internal static string CheckErrorLocked {
            get {
                return ResourceManager.GetString("CheckErrorLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The machine has changed since the licence was registered.  Please contact RainWorx support to resolve the issue..
        /// </summary>
        internal static string CheckErrorMachineChanged {
            get {
                return ResourceManager.GetString("CheckErrorMachineChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There were no unused clients remaining for the licence.  Please contact RainWorx support to resolve the issue..
        /// </summary>
        internal static string CheckErrorNoClientsRemaining {
            get {
                return ResourceManager.GetString("CheckErrorNoClientsRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The licence does not exist on the server.  Please contact RainWorx support to resolve the issue..
        /// </summary>
        internal static string CheckErrorNoSuchLicence {
            get {
                return ResourceManager.GetString("CheckErrorNoSuchLicence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The environment is Terminal Services or Citrix, but the licence is not for use under Citrix.  Please contact RainWorx support to resolve the issue..
        /// </summary>
        internal static string CheckErrorNotTSLicence {
            get {
                return ResourceManager.GetString("CheckErrorNotTSLicence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The environment is VMWare or MS Virtual PC, but the licence is not for use under virtualisation.  Please contact RainWorx support to resolve the issue..
        /// </summary>
        internal static string CheckErrorNotVirtualLicence {
            get {
                return ResourceManager.GetString("CheckErrorNotVirtualLicence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GearShift is not yet registered on this machine.  Please contact RainWorx support to resolve the issue..
        /// </summary>
        internal static string CheckErrorNotYetRegistered {
            get {
                return ResourceManager.GetString("CheckErrorNotYetRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The WMI service is not available on this machine.  WMI is required for licensing.  Please contact RainWorx support to resolve the issue..
        /// </summary>
        internal static string CheckErrorNoWmi {
            get {
                return ResourceManager.GetString("CheckErrorNoWmi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify WebProxyCredentials.  Please contact RainWorx support to resolve the issue..
        /// </summary>
        internal static string CheckErrorProxyAuthenticationRequired {
            get {
                return ResourceManager.GetString("CheckErrorProxyAuthenticationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It appears that either the licence, licence response, or cache has been tampered with.  Please contact RainWorx support to resolve the issue..
        /// </summary>
        internal static string CheckErrorTampered {
            get {
                return ResourceManager.GetString("CheckErrorTampered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unspecified licensing error occurred.  Please contact RainWorx support to resolve the issue..
        /// </summary>
        internal static string CheckErrorUnspecified {
            get {
                return ResourceManager.GetString("CheckErrorUnspecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The licence is for a different product.  Please contact RainWorx support to resolve the issue..
        /// </summary>
        internal static string CheckErrorWrongProduct {
            get {
                return ResourceManager.GetString("CheckErrorWrongProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The version of the application exceeds the maximum version of the licence.  Please contact RainWorx support to resolve the issue..
        /// </summary>
        internal static string CheckErrorWrongVersion {
            get {
                return ResourceManager.GetString("CheckErrorWrongVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Demo licence of GearShift is expired.  Please contact RainWorx support to resolve the issue..
        /// </summary>
        internal static string CheckFeatureDemoExpired {
            get {
                return ResourceManager.GetString("CheckFeatureDemoExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have a valid licence, but it does not grant you the right to use GearShift.  Please contact RainWorx support to resolve the issue..
        /// </summary>
        internal static string CheckFeatureNone {
            get {
                return ResourceManager.GetString("CheckFeatureNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Periodic license of GearShift is expired.  Please contact RainWorx support to resolve the issue..
        /// </summary>
        internal static string CheckFeaturePeriodicExpired {
            get {
                return ResourceManager.GetString("CheckFeaturePeriodicExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The licence server could not be contacted. Either the server does not have an active Internet connection, or a firewall is blocking communication.  Please contact RainWorx support to resolve the issue..
        /// </summary>
        internal static string RegisterErrorCouldNotConnect {
            get {
                return ResourceManager.GetString("RegisterErrorCouldNotConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To activate GearShift you must place your licence file in the location specified in the web.config file..
        /// </summary>
        internal static string RegisterErrorCouldNotReadLicence {
            get {
                return ResourceManager.GetString("RegisterErrorCouldNotReadLicence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An empty or null licence filename was passed.  Please contact RainWorx support to resolve the issue..
        /// </summary>
        internal static string RegisterErrorLicenceFilenameNullOrEmpty {
            get {
                return ResourceManager.GetString("RegisterErrorLicenceFilenameNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your licence has been disabled by RainWorx.  Please contact RainWorx support to resolve the issue..
        /// </summary>
        internal static string RegisterErrorLocked {
            get {
                return ResourceManager.GetString("RegisterErrorLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There were no unused clients remaining for the licence.  Please contact RainWorx support to resolve the issue..
        /// </summary>
        internal static string RegisterErrorNoClientsRemaining {
            get {
                return ResourceManager.GetString("RegisterErrorNoClientsRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The licence does not exist on the server.  Please contact RainWorx support to resolve the issue..
        /// </summary>
        internal static string RegisterErrorNoSuchLicence {
            get {
                return ResourceManager.GetString("RegisterErrorNoSuchLicence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The environment is Terminal Services or Citrix, but the licence is not for use under Citrix.  Please contact RainWorx support to resolve the issue..
        /// </summary>
        internal static string RegisterErrorNotTSLicence {
            get {
                return ResourceManager.GetString("RegisterErrorNotTSLicence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The environment is VMWare or MS Virtual PC, but the licence is not for use under virtualisation.  Please contact RainWorx support to resolve the issue..
        /// </summary>
        internal static string RegisterErrorNotVirtualLicence {
            get {
                return ResourceManager.GetString("RegisterErrorNotVirtualLicence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The WMI service is not available on this machine.  WMI is required for licensing.  Please contact RainWorx support to resolve the issue..
        /// </summary>
        internal static string RegisterErrorNoWmi {
            get {
                return ResourceManager.GetString("RegisterErrorNoWmi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify WebProxyCredentials.  Please contact RainWorx support to resolve the issue..
        /// </summary>
        internal static string RegisterErrorProxyAuthenticationRequired {
            get {
                return ResourceManager.GetString("RegisterErrorProxyAuthenticationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It appears that either the licence, licence response, or cache has been tampered with.  Please contact RainWorx support to resolve the issue..
        /// </summary>
        internal static string RegisterErrorTampered {
            get {
                return ResourceManager.GetString("RegisterErrorTampered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unspecified licensing error occurred.  Please contact RainWorx support to resolve the issue..
        /// </summary>
        internal static string RegisterErrorUnspecified {
            get {
                return ResourceManager.GetString("RegisterErrorUnspecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows 95, 98 and 98 SE are not supported.  Please contact RainWorx support to resolve the issue..
        /// </summary>
        internal static string RegisterErrorUnsupportedOS {
            get {
                return ResourceManager.GetString("RegisterErrorUnsupportedOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The version of the application exceeds the maximum version of the licence.  Please contact RainWorx support to resolve the issue..
        /// </summary>
        internal static string RegisterErrorWrongProduct {
            get {
                return ResourceManager.GetString("RegisterErrorWrongProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The version of the application exceeds the maximum version of the licence.  Please contact RainWorx support to resolve the issue..
        /// </summary>
        internal static string RegisterErrorWrongVersion {
            get {
                return ResourceManager.GetString("RegisterErrorWrongVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Demo licence of GearShift is expired.  Please contact RainWorx support to resolve the issue..
        /// </summary>
        internal static string RegisterFeatureDemoExpired {
            get {
                return ResourceManager.GetString("RegisterFeatureDemoExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have a valid licence, but it does not grant you the right to use GearShift.  Please contact RainWorx support to resolve the issue..
        /// </summary>
        internal static string RegisterFeatureNone {
            get {
                return ResourceManager.GetString("RegisterFeatureNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Periodic license of GearShift is expired.  Please contact RainWorx support to resolve the issue..
        /// </summary>
        internal static string RegisterFeaturePeriodicExpired {
            get {
                return ResourceManager.GetString("RegisterFeaturePeriodicExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully deactivated GearShift on this machine.  If you do not want it to automatically re-activate, please move your licence file now..
        /// </summary>
        internal static string Unregistered {
            get {
                return ResourceManager.GetString("Unregistered", resourceCulture);
            }
        }
    }
}
