//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ShippingOptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ShippingOptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ShippingOptions", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DHL Second Day.
        /// </summary>
        internal static string DHL2D {
            get {
                return ResourceManager.GetString("DHL2D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DHL Next Afternoon.
        /// </summary>
        internal static string DHLEXA {
            get {
                return ResourceManager.GetString("DHLEXA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DHL Express 10:30.
        /// </summary>
        internal static string DHLEXM {
            get {
                return ResourceManager.GetString("DHLEXM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DHL Express.
        /// </summary>
        internal static string DHLEXP {
            get {
                return ResourceManager.GetString("DHLEXP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DHL Ground.
        /// </summary>
        internal static string DHLGND {
            get {
                return ResourceManager.GetString("DHLGND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DHL Worldwide Priority Express.
        /// </summary>
        internal static string DHLWPE {
            get {
                return ResourceManager.GetString("DHLWPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FEDEX 2 Day.
        /// </summary>
        internal static string FDX2D {
            get {
                return ResourceManager.GetString("FDX2D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FEDEX Express Saver.
        /// </summary>
        internal static string FDXES {
            get {
                return ResourceManager.GetString("FDXES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FEDEX First Overnight.
        /// </summary>
        internal static string FDXFO {
            get {
                return ResourceManager.GetString("FDXFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FEDEX Ground.
        /// </summary>
        internal static string FDXGND {
            get {
                return ResourceManager.GetString("FDXGND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FEDEX Home Delivery.
        /// </summary>
        internal static string FDXHD {
            get {
                return ResourceManager.GetString("FDXHD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FEDEX International Economy.
        /// </summary>
        internal static string FDXIE {
            get {
                return ResourceManager.GetString("FDXIE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FEDEX International First.
        /// </summary>
        internal static string FDXIF {
            get {
                return ResourceManager.GetString("FDXIF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FEDEX International Ground.
        /// </summary>
        internal static string FDXIGND {
            get {
                return ResourceManager.GetString("FDXIGND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FEDEX International Priority.
        /// </summary>
        internal static string FDXIP {
            get {
                return ResourceManager.GetString("FDXIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FEDEX Priority Overnight.
        /// </summary>
        internal static string FDXPO {
            get {
                return ResourceManager.GetString("FDXPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FEDEX Priority Overnight Saturday Delivery.
        /// </summary>
        internal static string FDXPOS {
            get {
                return ResourceManager.GetString("FDXPOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FEDEX Standard Overnight.
        /// </summary>
        internal static string FDXSO {
            get {
                return ResourceManager.GetString("FDXSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPS 2 Day Air AM (commercial destinations only).
        /// </summary>
        internal static string UPS2DE {
            get {
                return ResourceManager.GetString("UPS2DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2nd Day Air.
        /// </summary>
        internal static string UPS2ND {
            get {
                return ResourceManager.GetString("UPS2ND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPS 3 Day Select.
        /// </summary>
        internal static string UPS3DS {
            get {
                return ResourceManager.GetString("UPS3DS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPS Canada Standard.
        /// </summary>
        internal static string UPSCAN {
            get {
                return ResourceManager.GetString("UPSCAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPS Ground.
        /// </summary>
        internal static string UPSGND {
            get {
                return ResourceManager.GetString("UPSGND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPS Next Day Air.
        /// </summary>
        internal static string UPSNDA {
            get {
                return ResourceManager.GetString("UPSNDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPS Next Day Saturday Delivery.
        /// </summary>
        internal static string UPSNDAS {
            get {
                return ResourceManager.GetString("UPSNDAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPS Next Day Early AM.
        /// </summary>
        internal static string UPSNDE {
            get {
                return ResourceManager.GetString("UPSNDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPS Next Day Saver.
        /// </summary>
        internal static string UPSNDS {
            get {
                return ResourceManager.GetString("UPSNDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPS Worldwide Expedited.
        /// </summary>
        internal static string UPSWEP {
            get {
                return ResourceManager.GetString("UPSWEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPS Worldwide Express.
        /// </summary>
        internal static string UPSWEX {
            get {
                return ResourceManager.GetString("UPSWEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPS Worldwide Saver.
        /// </summary>
        internal static string UPSWSV {
            get {
                return ResourceManager.GetString("UPSWSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USPS Bound/Printed.
        /// </summary>
        internal static string USPBPM {
            get {
                return ResourceManager.GetString("USPBPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USPS Express Mail International.
        /// </summary>
        internal static string USPEMI {
            get {
                return ResourceManager.GetString("USPEMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USPS Express Mail.
        /// </summary>
        internal static string USPEXP {
            get {
                return ResourceManager.GetString("USPEXP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USPS First-Class Mail.
        /// </summary>
        internal static string USPFC {
            get {
                return ResourceManager.GetString("USPFC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USPS First Class International.
        /// </summary>
        internal static string USPFCI {
            get {
                return ResourceManager.GetString("USPFCI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USPS Global Express Guaranteed.
        /// </summary>
        internal static string USPGXG {
            get {
                return ResourceManager.GetString("USPGXG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USPS Library.
        /// </summary>
        internal static string USPLIB {
            get {
                return ResourceManager.GetString("USPLIB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USPS Media Mail.
        /// </summary>
        internal static string USPMM {
            get {
                return ResourceManager.GetString("USPMM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USPS Priority Mail.
        /// </summary>
        internal static string USPPM {
            get {
                return ResourceManager.GetString("USPPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USPS Priority Mail International.
        /// </summary>
        internal static string USPPMI {
            get {
                return ResourceManager.GetString("USPPMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USPS Parcel Post.
        /// </summary>
        internal static string USPPP {
            get {
                return ResourceManager.GetString("USPPP", resourceCulture);
            }
        }
    }
}
