//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class States {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal States() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.States", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALABAMA.
        /// </summary>
        internal static string ALABAMA {
            get {
                return ResourceManager.GetString("ALABAMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALASKA.
        /// </summary>
        internal static string ALASKA {
            get {
                return ResourceManager.GetString("ALASKA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AMERICAN SAMOA.
        /// </summary>
        internal static string AMERICAN_SAMOA {
            get {
                return ResourceManager.GetString("AMERICAN_SAMOA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ARIZONA.
        /// </summary>
        internal static string ARIZONA_ {
            get {
                return ResourceManager.GetString("ARIZONA_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ARKANSAS.
        /// </summary>
        internal static string ARKANSAS {
            get {
                return ResourceManager.GetString("ARKANSAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armed Forces Africa.
        /// </summary>
        internal static string Armed_Forces_Africa {
            get {
                return ResourceManager.GetString("Armed_Forces_Africa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armed Forces Americas (except Canada).
        /// </summary>
        internal static string Armed_Forces_Americas__except_Canada_ {
            get {
                return ResourceManager.GetString("Armed_Forces_Americas__except_Canada_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armed Forces Canada.
        /// </summary>
        internal static string Armed_Forces_Canada {
            get {
                return ResourceManager.GetString("Armed_Forces_Canada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armed Forces Europe.
        /// </summary>
        internal static string Armed_Forces_Europe {
            get {
                return ResourceManager.GetString("Armed_Forces_Europe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armed Forces Middle East.
        /// </summary>
        internal static string Armed_Forces_Middle_East {
            get {
                return ResourceManager.GetString("Armed_Forces_Middle_East", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armed Forces Pacific.
        /// </summary>
        internal static string Armed_Forces_Pacific {
            get {
                return ResourceManager.GetString("Armed_Forces_Pacific", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CALIFORNIA.
        /// </summary>
        internal static string CALIFORNIA_ {
            get {
                return ResourceManager.GetString("CALIFORNIA_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COLORADO.
        /// </summary>
        internal static string COLORADO_ {
            get {
                return ResourceManager.GetString("COLORADO_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONNECTICUT.
        /// </summary>
        internal static string CONNECTICUT {
            get {
                return ResourceManager.GetString("CONNECTICUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELAWARE.
        /// </summary>
        internal static string DELAWARE {
            get {
                return ResourceManager.GetString("DELAWARE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DISTRICT OF COLUMBIA.
        /// </summary>
        internal static string DISTRICT_OF_COLUMBIA {
            get {
                return ResourceManager.GetString("DISTRICT_OF_COLUMBIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FEDERATED STATES OF MICRONESIA.
        /// </summary>
        internal static string FEDERATED_STATES_OF_MICRONESIA {
            get {
                return ResourceManager.GetString("FEDERATED_STATES_OF_MICRONESIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FLORIDA.
        /// </summary>
        internal static string FLORIDA {
            get {
                return ResourceManager.GetString("FLORIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GEORGIA.
        /// </summary>
        internal static string GEORGIA {
            get {
                return ResourceManager.GetString("GEORGIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GUAM.
        /// </summary>
        internal static string GUAM_ {
            get {
                return ResourceManager.GetString("GUAM_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HAWAII.
        /// </summary>
        internal static string HAWAII {
            get {
                return ResourceManager.GetString("HAWAII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IDAHO.
        /// </summary>
        internal static string IDAHO {
            get {
                return ResourceManager.GetString("IDAHO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ILLINOIS.
        /// </summary>
        internal static string ILLINOIS {
            get {
                return ResourceManager.GetString("ILLINOIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INDIANA.
        /// </summary>
        internal static string INDIANA {
            get {
                return ResourceManager.GetString("INDIANA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IOWA.
        /// </summary>
        internal static string IOWA {
            get {
                return ResourceManager.GetString("IOWA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KANSAS.
        /// </summary>
        internal static string KANSAS {
            get {
                return ResourceManager.GetString("KANSAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KENTUCKY.
        /// </summary>
        internal static string KENTUCKY {
            get {
                return ResourceManager.GetString("KENTUCKY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOUISIANA.
        /// </summary>
        internal static string LOUISIANA {
            get {
                return ResourceManager.GetString("LOUISIANA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAINE.
        /// </summary>
        internal static string MAINE {
            get {
                return ResourceManager.GetString("MAINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MARSHALL ISLANDS.
        /// </summary>
        internal static string MARSHALL_ISLANDS {
            get {
                return ResourceManager.GetString("MARSHALL_ISLANDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MARYLAND.
        /// </summary>
        internal static string MARYLAND {
            get {
                return ResourceManager.GetString("MARYLAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MASSACHUSETTS.
        /// </summary>
        internal static string MASSACHUSETTS {
            get {
                return ResourceManager.GetString("MASSACHUSETTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MICHIGAN.
        /// </summary>
        internal static string MICHIGAN {
            get {
                return ResourceManager.GetString("MICHIGAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MINNESOTA.
        /// </summary>
        internal static string MINNESOTA {
            get {
                return ResourceManager.GetString("MINNESOTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MISSISSIPPI.
        /// </summary>
        internal static string MISSISSIPPI {
            get {
                return ResourceManager.GetString("MISSISSIPPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MISSOURI.
        /// </summary>
        internal static string MISSOURI {
            get {
                return ResourceManager.GetString("MISSOURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MONTANA.
        /// </summary>
        internal static string MONTANA {
            get {
                return ResourceManager.GetString("MONTANA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEBRASKA.
        /// </summary>
        internal static string NEBRASKA {
            get {
                return ResourceManager.GetString("NEBRASKA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEVADA.
        /// </summary>
        internal static string NEVADA {
            get {
                return ResourceManager.GetString("NEVADA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEW HAMPSHIRE.
        /// </summary>
        internal static string NEW_HAMPSHIRE {
            get {
                return ResourceManager.GetString("NEW_HAMPSHIRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEW JERSEY.
        /// </summary>
        internal static string NEW_JERSEY {
            get {
                return ResourceManager.GetString("NEW_JERSEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEW MEXICO.
        /// </summary>
        internal static string NEW_MEXICO {
            get {
                return ResourceManager.GetString("NEW_MEXICO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEW YORK.
        /// </summary>
        internal static string NEW_YORK {
            get {
                return ResourceManager.GetString("NEW_YORK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NORTHERN MARIANA ISLANDS.
        /// </summary>
        internal static string NORTHERN_MARIANA_ISLANDS {
            get {
                return ResourceManager.GetString("NORTHERN_MARIANA_ISLANDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NORTH CAROLINA.
        /// </summary>
        internal static string NORTH_CAROLINA {
            get {
                return ResourceManager.GetString("NORTH_CAROLINA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NORTH DAKOTA.
        /// </summary>
        internal static string NORTH_DAKOTA {
            get {
                return ResourceManager.GetString("NORTH_DAKOTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OHIO.
        /// </summary>
        internal static string OHIO {
            get {
                return ResourceManager.GetString("OHIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OKLAHOMA.
        /// </summary>
        internal static string OKLAHOMA {
            get {
                return ResourceManager.GetString("OKLAHOMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OREGON.
        /// </summary>
        internal static string OREGON {
            get {
                return ResourceManager.GetString("OREGON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PALAU.
        /// </summary>
        internal static string PALAU {
            get {
                return ResourceManager.GetString("PALAU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PENNSYLVANIA.
        /// </summary>
        internal static string PENNSYLVANIA {
            get {
                return ResourceManager.GetString("PENNSYLVANIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PUERTO RICO.
        /// </summary>
        internal static string PUERTO_RICO {
            get {
                return ResourceManager.GetString("PUERTO_RICO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RHODE ISLAND.
        /// </summary>
        internal static string RHODE_ISLAND {
            get {
                return ResourceManager.GetString("RHODE_ISLAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOUTH CAROLINA.
        /// </summary>
        internal static string SOUTH_CAROLINA {
            get {
                return ResourceManager.GetString("SOUTH_CAROLINA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOUTH DAKOTA.
        /// </summary>
        internal static string SOUTH_DAKOTA {
            get {
                return ResourceManager.GetString("SOUTH_DAKOTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TENNESSEE.
        /// </summary>
        internal static string TENNESSEE {
            get {
                return ResourceManager.GetString("TENNESSEE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEXAS.
        /// </summary>
        internal static string TEXAS {
            get {
                return ResourceManager.GetString("TEXAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UTAH.
        /// </summary>
        internal static string UTAH {
            get {
                return ResourceManager.GetString("UTAH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VERMONT.
        /// </summary>
        internal static string VERMONT {
            get {
                return ResourceManager.GetString("VERMONT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIRGINIA.
        /// </summary>
        internal static string VIRGINIA_ {
            get {
                return ResourceManager.GetString("VIRGINIA_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIRGIN ISLANDS.
        /// </summary>
        internal static string VIRGIN_ISLANDS {
            get {
                return ResourceManager.GetString("VIRGIN_ISLANDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WASHINGTON.
        /// </summary>
        internal static string WASHINGTON {
            get {
                return ResourceManager.GetString("WASHINGTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WEST VIRGINIA.
        /// </summary>
        internal static string WEST_VIRGINIA {
            get {
                return ResourceManager.GetString("WEST_VIRGINIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WISCONSIN.
        /// </summary>
        internal static string WISCONSIN {
            get {
                return ResourceManager.GetString("WISCONSIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WYOMING.
        /// </summary>
        internal static string WYOMING {
            get {
                return ResourceManager.GetString("WYOMING", resourceCulture);
            }
        }
    }
}
