//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TimeZones {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TimeZones() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.TimeZones", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kabul.
        /// </summary>
        internal static string Afghanistan_Standard_Time {
            get {
                return ResourceManager.GetString("Afghanistan_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AFG.
        /// </summary>
        internal static string Afghanistan_Standard_Time_Short {
            get {
                return ResourceManager.GetString("Afghanistan_Standard_Time_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alaska.
        /// </summary>
        internal static string Alaskan_Standard_Time {
            get {
                return ResourceManager.GetString("Alaskan_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AKT.
        /// </summary>
        internal static string Alaskan_Standard_Time_Short {
            get {
                return ResourceManager.GetString("Alaskan_Standard_Time_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abu Dhabi, Muscat.
        /// </summary>
        internal static string Arabian_Standard_Time {
            get {
                return ResourceManager.GetString("Arabian_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ARB.
        /// </summary>
        internal static string Arabian_Standard_Time_Short {
            get {
                return ResourceManager.GetString("Arabian_Standard_Time_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baghdad.
        /// </summary>
        internal static string Arabic_Standard_Time {
            get {
                return ResourceManager.GetString("Arabic_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ARB.
        /// </summary>
        internal static string Arabic_Standard_Time_Short {
            get {
                return ResourceManager.GetString("Arabic_Standard_Time_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kuwait, Riyadh.
        /// </summary>
        internal static string Arab_Standard_Time {
            get {
                return ResourceManager.GetString("Arab_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ARB.
        /// </summary>
        internal static string Arab_Standard_Time_Short {
            get {
                return ResourceManager.GetString("Arab_Standard_Time_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buenos Aires.
        /// </summary>
        internal static string Argentina_Standard_Time {
            get {
                return ResourceManager.GetString("Argentina_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AGT.
        /// </summary>
        internal static string Argentina_Standard_Time_Short {
            get {
                return ResourceManager.GetString("Argentina_Standard_Time_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atlantic Time (Canada).
        /// </summary>
        internal static string Atlantic_Standard_Time {
            get {
                return ResourceManager.GetString("Atlantic_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AT.
        /// </summary>
        internal static string Atlantic_Standard_Time_Short {
            get {
                return ResourceManager.GetString("Atlantic_Standard_Time_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Darwin.
        /// </summary>
        internal static string AUS_Central_Standard_Time {
            get {
                return ResourceManager.GetString("AUS_Central_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAUS.
        /// </summary>
        internal static string AUS_Central_Standard_Time_Short {
            get {
                return ResourceManager.GetString("AUS_Central_Standard_Time_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canberra, Melbourne, Sydney.
        /// </summary>
        internal static string AUS_Eastern_Standard_Time {
            get {
                return ResourceManager.GetString("AUS_Eastern_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EAUS.
        /// </summary>
        internal static string AUS_Eastern_Standard_Time_Short {
            get {
                return ResourceManager.GetString("AUS_Eastern_Standard_Time_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baku.
        /// </summary>
        internal static string Azerbaijan_Standard_Time {
            get {
                return ResourceManager.GetString("Azerbaijan_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AZBJ.
        /// </summary>
        internal static string Azerbaijan_Standard_Time_Short {
            get {
                return ResourceManager.GetString("Azerbaijan_Standard_Time_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azores.
        /// </summary>
        internal static string Azores_Standard_Time {
            get {
                return ResourceManager.GetString("Azores_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AZT.
        /// </summary>
        internal static string Azores_Standard_Time_Short {
            get {
                return ResourceManager.GetString("Azores_Standard_Time_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvador.
        /// </summary>
        internal static string Bahia_Standard_Time {
            get {
                return ResourceManager.GetString("Bahia_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BHT.
        /// </summary>
        internal static string Bahia_Standard_Time_Short {
            get {
                return ResourceManager.GetString("Bahia_Standard_Time_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dhaka.
        /// </summary>
        internal static string Bangladesh_Standard_Time {
            get {
                return ResourceManager.GetString("Bangladesh_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BNGL.
        /// </summary>
        internal static string Bangladesh_Standard_Time_Short {
            get {
                return ResourceManager.GetString("Bangladesh_Standard_Time_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minsk.
        /// </summary>
        internal static string Belarus_Standard_Time {
            get {
                return ResourceManager.GetString("Belarus_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BELR.
        /// </summary>
        internal static string Belarus_Standard_Time_Short {
            get {
                return ResourceManager.GetString("Belarus_Standard_Time_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saskatchewan.
        /// </summary>
        internal static string Canada_Central_Standard_Time {
            get {
                return ResourceManager.GetString("Canada_Central_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CTC.
        /// </summary>
        internal static string Canada_Central_Standard_Time_Short {
            get {
                return ResourceManager.GetString("Canada_Central_Standard_Time_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cabo Verde Is..
        /// </summary>
        internal static string Cape_Verde_Standard_Time {
            get {
                return ResourceManager.GetString("Cape_Verde_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CVT.
        /// </summary>
        internal static string Cape_Verde_Standard_Time_Short {
            get {
                return ResourceManager.GetString("Cape_Verde_Standard_Time_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yerevan.
        /// </summary>
        internal static string Caucasus_Standard_Time {
            get {
                return ResourceManager.GetString("Caucasus_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAUC.
        /// </summary>
        internal static string Caucasus_Standard_Time_Short {
            get {
                return ResourceManager.GetString("Caucasus_Standard_Time_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Central America.
        /// </summary>
        internal static string Central_America_Standard_Time {
            get {
                return ResourceManager.GetString("Central_America_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAT.
        /// </summary>
        internal static string Central_America_Standard_Time_Short {
            get {
                return ResourceManager.GetString("Central_America_Standard_Time_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Astana.
        /// </summary>
        internal static string Central_Asia_Standard_Time {
            get {
                return ResourceManager.GetString("Central_Asia_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CASIA.
        /// </summary>
        internal static string Central_Asia_Standard_Time_Short {
            get {
                return ResourceManager.GetString("Central_Asia_Standard_Time_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuiaba.
        /// </summary>
        internal static string Central_Brazilian_Standard_Time {
            get {
                return ResourceManager.GetString("Central_Brazilian_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CBZ.
        /// </summary>
        internal static string Central_Brazilian_Standard_Time_Short {
            get {
                return ResourceManager.GetString("Central_Brazilian_Standard_Time_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sarajevo, Skopje, Warsaw, Zagreb.
        /// </summary>
        internal static string Central_European_Standard_Time {
            get {
                return ResourceManager.GetString("Central_European_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CET.
        /// </summary>
        internal static string Central_European_Standard_Time_Short {
            get {
                return ResourceManager.GetString("Central_European_Standard_Time_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belgrade, Bratislava, Budapest, Ljubljana, Prague.
        /// </summary>
        internal static string Central_Europe_Standard_Time {
            get {
                return ResourceManager.GetString("Central_Europe_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CET.
        /// </summary>
        internal static string Central_Europe_Standard_Time_Short {
            get {
                return ResourceManager.GetString("Central_Europe_Standard_Time_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solomon Is., New Caledonia.
        /// </summary>
        internal static string Central_Pacific_Standard_Time {
            get {
                return ResourceManager.GetString("Central_Pacific_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPAC.
        /// </summary>
        internal static string Central_Pacific_Standard_Time_Short {
            get {
                return ResourceManager.GetString("Central_Pacific_Standard_Time_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Central Standard Time.
        /// </summary>
        internal static string Central_Standard_Time {
            get {
                return ResourceManager.GetString("Central_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guadalajara, Mexico City, Monterrey.
        /// </summary>
        internal static string Central_Standard_Time_Mexico {
            get {
                return ResourceManager.GetString("Central_Standard_Time_Mexico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CTM.
        /// </summary>
        internal static string Central_Standard_Time_Mexico_Short {
            get {
                return ResourceManager.GetString("Central_Standard_Time_Mexico_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CT.
        /// </summary>
        internal static string Central_Standard_Time_Short {
            get {
                return ResourceManager.GetString("Central_Standard_Time_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adelaide.
        /// </summary>
        internal static string Cen_Australia_Standard_Time {
            get {
                return ResourceManager.GetString("Cen_Australia_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAUS.
        /// </summary>
        internal static string Cen_Australia_Standard_Time_Short {
            get {
                return ResourceManager.GetString("Cen_Australia_Standard_Time_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beijing, Chongqing, Hong Kong, Urumqi.
        /// </summary>
        internal static string China_Standard_Time {
            get {
                return ResourceManager.GetString("China_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHN.
        /// </summary>
        internal static string China_Standard_Time_Short {
            get {
                return ResourceManager.GetString("China_Standard_Time_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to International Date Line West.
        /// </summary>
        internal static string Dateline_Standard_Time {
            get {
                return ResourceManager.GetString("Dateline_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AoE.
        /// </summary>
        internal static string Dateline_Standard_Time_Short {
            get {
                return ResourceManager.GetString("Dateline_Standard_Time_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eastern Time (US &amp; Canada).
        /// </summary>
        internal static string Eastern_Standard_Time {
            get {
                return ResourceManager.GetString("Eastern_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chetumal.
        /// </summary>
        internal static string Eastern_Standard_Time_Mexico {
            get {
                return ResourceManager.GetString("Eastern_Standard_Time_Mexico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ETM.
        /// </summary>
        internal static string Eastern_Standard_Time_Mexico_Short {
            get {
                return ResourceManager.GetString("Eastern_Standard_Time_Mexico_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ET.
        /// </summary>
        internal static string Eastern_Standard_Time_Short {
            get {
                return ResourceManager.GetString("Eastern_Standard_Time_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cairo.
        /// </summary>
        internal static string Egypt_Standard_Time {
            get {
                return ResourceManager.GetString("Egypt_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EGP.
        /// </summary>
        internal static string Egypt_Standard_Time_Short {
            get {
                return ResourceManager.GetString("Egypt_Standard_Time_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekaterinburg (RTZ 4).
        /// </summary>
        internal static string Ekaterinburg_Standard_Time {
            get {
                return ResourceManager.GetString("Ekaterinburg_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RTZ4.
        /// </summary>
        internal static string Ekaterinburg_Standard_Time_Short {
            get {
                return ResourceManager.GetString("Ekaterinburg_Standard_Time_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nairobi.
        /// </summary>
        internal static string E_Africa_Standard_Time {
            get {
                return ResourceManager.GetString("E_Africa_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EAF.
        /// </summary>
        internal static string E_Africa_Standard_Time_Short {
            get {
                return ResourceManager.GetString("E_Africa_Standard_Time_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brisbane.
        /// </summary>
        internal static string E_Australia_Standard_Time {
            get {
                return ResourceManager.GetString("E_Australia_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EAUS.
        /// </summary>
        internal static string E_Australia_Standard_Time_Short {
            get {
                return ResourceManager.GetString("E_Australia_Standard_Time_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E. Europe.
        /// </summary>
        internal static string E_Europe_Standard_Time {
            get {
                return ResourceManager.GetString("E_Europe_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EEUR.
        /// </summary>
        internal static string E_Europe_Standard_Time_Short {
            get {
                return ResourceManager.GetString("E_Europe_Standard_Time_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brasilia.
        /// </summary>
        internal static string E_South_America_Standard_Time {
            get {
                return ResourceManager.GetString("E_South_America_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESAT.
        /// </summary>
        internal static string E_South_America_Standard_Time_Short {
            get {
                return ResourceManager.GetString("E_South_America_Standard_Time_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiji.
        /// </summary>
        internal static string Fiji_Standard_Time {
            get {
                return ResourceManager.GetString("Fiji_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FJT.
        /// </summary>
        internal static string Fiji_Standard_Time_Short {
            get {
                return ResourceManager.GetString("Fiji_Standard_Time_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius.
        /// </summary>
        internal static string FLE_Standard_Time {
            get {
                return ResourceManager.GetString("FLE_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FLE.
        /// </summary>
        internal static string FLE_Standard_Time_Short {
            get {
                return ResourceManager.GetString("FLE_Standard_Time_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tbilisi.
        /// </summary>
        internal static string Georgian_Standard_Time {
            get {
                return ResourceManager.GetString("Georgian_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GRG.
        /// </summary>
        internal static string Georgian_Standard_Time_Short {
            get {
                return ResourceManager.GetString("Georgian_Standard_Time_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dublin, Edinburgh, Lisbon, London.
        /// </summary>
        internal static string GMT_Standard_Time {
            get {
                return ResourceManager.GetString("GMT_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GMT.
        /// </summary>
        internal static string GMT_Standard_Time_Short {
            get {
                return ResourceManager.GetString("GMT_Standard_Time_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greenland.
        /// </summary>
        internal static string Greenland_Standard_Time {
            get {
                return ResourceManager.GetString("Greenland_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GRT.
        /// </summary>
        internal static string Greenland_Standard_Time_Short {
            get {
                return ResourceManager.GetString("Greenland_Standard_Time_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monrovia, Reykjavik.
        /// </summary>
        internal static string Greenwich_Standard_Time {
            get {
                return ResourceManager.GetString("Greenwich_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GT.
        /// </summary>
        internal static string Greenwich_Standard_Time_Short {
            get {
                return ResourceManager.GetString("Greenwich_Standard_Time_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Athens, Bucharest.
        /// </summary>
        internal static string GTB_Standard_Time {
            get {
                return ResourceManager.GetString("GTB_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GTB.
        /// </summary>
        internal static string GTB_Standard_Time_Short {
            get {
                return ResourceManager.GetString("GTB_Standard_Time_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hawaii.
        /// </summary>
        internal static string Hawaiian_Standard_Time {
            get {
                return ResourceManager.GetString("Hawaiian_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HWT.
        /// </summary>
        internal static string Hawaiian_Standard_Time_Short {
            get {
                return ResourceManager.GetString("Hawaiian_Standard_Time_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chennai, Kolkata, Mumbai, New Delhi.
        /// </summary>
        internal static string India_Standard_Time {
            get {
                return ResourceManager.GetString("India_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IND.
        /// </summary>
        internal static string India_Standard_Time_Short {
            get {
                return ResourceManager.GetString("India_Standard_Time_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tehran.
        /// </summary>
        internal static string Iran_Standard_Time {
            get {
                return ResourceManager.GetString("Iran_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IRN.
        /// </summary>
        internal static string Iran_Standard_Time_Short {
            get {
                return ResourceManager.GetString("Iran_Standard_Time_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jerusalem.
        /// </summary>
        internal static string Israel_Standard_Time {
            get {
                return ResourceManager.GetString("Israel_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISR.
        /// </summary>
        internal static string Israel_Standard_Time_Short {
            get {
                return ResourceManager.GetString("Israel_Standard_Time_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amman.
        /// </summary>
        internal static string Jordan_Standard_Time {
            get {
                return ResourceManager.GetString("Jordan_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JOR.
        /// </summary>
        internal static string Jordan_Standard_Time_Short {
            get {
                return ResourceManager.GetString("Jordan_Standard_Time_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaliningrad (RTZ 1).
        /// </summary>
        internal static string Kaliningrad_Standard_Time {
            get {
                return ResourceManager.GetString("Kaliningrad_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RTZ1.
        /// </summary>
        internal static string Kaliningrad_Standard_Time_Short {
            get {
                return ResourceManager.GetString("Kaliningrad_Standard_Time_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Petropavlovsk-Kamchatsky - Old.
        /// </summary>
        internal static string Kamchatka_Standard_Time {
            get {
                return ResourceManager.GetString("Kamchatka_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KMCH.
        /// </summary>
        internal static string Kamchatka_Standard_Time_Short {
            get {
                return ResourceManager.GetString("Kamchatka_Standard_Time_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seoul.
        /// </summary>
        internal static string Korea_Standard_Time {
            get {
                return ResourceManager.GetString("Korea_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KOR.
        /// </summary>
        internal static string Korea_Standard_Time_Short {
            get {
                return ResourceManager.GetString("Korea_Standard_Time_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tripoli.
        /// </summary>
        internal static string Libya_Standard_Time {
            get {
                return ResourceManager.GetString("Libya_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LIB.
        /// </summary>
        internal static string Libya_Standard_Time_Short {
            get {
                return ResourceManager.GetString("Libya_Standard_Time_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiritimati Island.
        /// </summary>
        internal static string Line_Islands_Standard_Time {
            get {
                return ResourceManager.GetString("Line_Islands_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LIT.
        /// </summary>
        internal static string Line_Islands_Standard_Time_Short {
            get {
                return ResourceManager.GetString("Line_Islands_Standard_Time_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magadan.
        /// </summary>
        internal static string Magadan_Standard_Time {
            get {
                return ResourceManager.GetString("Magadan_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MGD.
        /// </summary>
        internal static string Magadan_Standard_Time_Short {
            get {
                return ResourceManager.GetString("Magadan_Standard_Time_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port Louis.
        /// </summary>
        internal static string Mauritius_Standard_Time {
            get {
                return ResourceManager.GetString("Mauritius_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MRT.
        /// </summary>
        internal static string Mauritius_Standard_Time_Short {
            get {
                return ResourceManager.GetString("Mauritius_Standard_Time_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mid-Atlantic - Old.
        /// </summary>
        internal static string MidAtlantic_Standard_Time {
            get {
                return ResourceManager.GetString("MidAtlantic_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAT.
        /// </summary>
        internal static string MidAtlantic_Standard_Time_Short {
            get {
                return ResourceManager.GetString("MidAtlantic_Standard_Time_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beirut.
        /// </summary>
        internal static string Middle_East_Standard_Time {
            get {
                return ResourceManager.GetString("Middle_East_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MET.
        /// </summary>
        internal static string Middle_East_Standard_Time_Short {
            get {
                return ResourceManager.GetString("Middle_East_Standard_Time_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Montevideo.
        /// </summary>
        internal static string Montevideo_Standard_Time {
            get {
                return ResourceManager.GetString("Montevideo_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MVT.
        /// </summary>
        internal static string Montevideo_Standard_Time_Short {
            get {
                return ResourceManager.GetString("Montevideo_Standard_Time_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Casablanca.
        /// </summary>
        internal static string Morocco_Standard_Time {
            get {
                return ResourceManager.GetString("Morocco_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MORT.
        /// </summary>
        internal static string Morocco_Standard_Time_Short {
            get {
                return ResourceManager.GetString("Morocco_Standard_Time_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mountain Time (US &amp; Canada).
        /// </summary>
        internal static string Mountain_Standard_Time {
            get {
                return ResourceManager.GetString("Mountain_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chihuahua, La Paz, Mazatlan.
        /// </summary>
        internal static string Mountain_Standard_Time_Mexico {
            get {
                return ResourceManager.GetString("Mountain_Standard_Time_Mexico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MTM.
        /// </summary>
        internal static string Mountain_Standard_Time_Mexico_Short {
            get {
                return ResourceManager.GetString("Mountain_Standard_Time_Mexico_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MT.
        /// </summary>
        internal static string Mountain_Standard_Time_Short {
            get {
                return ResourceManager.GetString("Mountain_Standard_Time_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yangon (Rangoon).
        /// </summary>
        internal static string Myanmar_Standard_Time {
            get {
                return ResourceManager.GetString("Myanmar_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MYMR.
        /// </summary>
        internal static string Myanmar_Standard_Time_Short {
            get {
                return ResourceManager.GetString("Myanmar_Standard_Time_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windhoek.
        /// </summary>
        internal static string Namibia_Standard_Time {
            get {
                return ResourceManager.GetString("Namibia_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NMB.
        /// </summary>
        internal static string Namibia_Standard_Time_Short {
            get {
                return ResourceManager.GetString("Namibia_Standard_Time_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kathmandu.
        /// </summary>
        internal static string Nepal_Standard_Time {
            get {
                return ResourceManager.GetString("Nepal_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NPL.
        /// </summary>
        internal static string Nepal_Standard_Time_Short {
            get {
                return ResourceManager.GetString("Nepal_Standard_Time_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newfoundland.
        /// </summary>
        internal static string Newfoundland_Standard_Time {
            get {
                return ResourceManager.GetString("Newfoundland_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NFT.
        /// </summary>
        internal static string Newfoundland_Standard_Time_Short {
            get {
                return ResourceManager.GetString("Newfoundland_Standard_Time_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auckland, Wellington.
        /// </summary>
        internal static string New_Zealand_Standard_Time {
            get {
                return ResourceManager.GetString("New_Zealand_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NZT.
        /// </summary>
        internal static string New_Zealand_Standard_Time_Short {
            get {
                return ResourceManager.GetString("New_Zealand_Standard_Time_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Irkutsk (RTZ 7).
        /// </summary>
        internal static string North_Asia_East_Standard_Time {
            get {
                return ResourceManager.GetString("North_Asia_East_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NASIA.
        /// </summary>
        internal static string North_Asia_East_Standard_Time_Short {
            get {
                return ResourceManager.GetString("North_Asia_East_Standard_Time_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Krasnoyarsk (RTZ 6).
        /// </summary>
        internal static string North_Asia_Standard_Time {
            get {
                return ResourceManager.GetString("North_Asia_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NASIA.
        /// </summary>
        internal static string North_Asia_Standard_Time_Short {
            get {
                return ResourceManager.GetString("North_Asia_Standard_Time_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novosibirsk (RTZ 5).
        /// </summary>
        internal static string N_Central_Asia_Standard_Time {
            get {
                return ResourceManager.GetString("N_Central_Asia_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RTZ5.
        /// </summary>
        internal static string N_Central_Asia_Standard_Time_Short {
            get {
                return ResourceManager.GetString("N_Central_Asia_Standard_Time_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Santiago.
        /// </summary>
        internal static string Pacific_SA_Standard_Time {
            get {
                return ResourceManager.GetString("Pacific_SA_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAPT.
        /// </summary>
        internal static string Pacific_SA_Standard_Time_Short {
            get {
                return ResourceManager.GetString("Pacific_SA_Standard_Time_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pacific Time (US &amp; Canada).
        /// </summary>
        internal static string Pacific_Standard_Time {
            get {
                return ResourceManager.GetString("Pacific_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baja California.
        /// </summary>
        internal static string Pacific_Standard_Time_Mexico {
            get {
                return ResourceManager.GetString("Pacific_Standard_Time_Mexico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PTM.
        /// </summary>
        internal static string Pacific_Standard_Time_Mexico_Short {
            get {
                return ResourceManager.GetString("Pacific_Standard_Time_Mexico_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PT.
        /// </summary>
        internal static string Pacific_Standard_Time_Short {
            get {
                return ResourceManager.GetString("Pacific_Standard_Time_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Islamabad, Karachi.
        /// </summary>
        internal static string Pakistan_Standard_Time {
            get {
                return ResourceManager.GetString("Pakistan_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAK.
        /// </summary>
        internal static string Pakistan_Standard_Time_Short {
            get {
                return ResourceManager.GetString("Pakistan_Standard_Time_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asuncion.
        /// </summary>
        internal static string Paraguay_Standard_Time {
            get {
                return ResourceManager.GetString("Paraguay_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PGT.
        /// </summary>
        internal static string Paraguay_Standard_Time_Short {
            get {
                return ResourceManager.GetString("Paraguay_Standard_Time_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brussels, Copenhagen, Madrid, Paris.
        /// </summary>
        internal static string Romance_Standard_Time {
            get {
                return ResourceManager.GetString("Romance_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RMT.
        /// </summary>
        internal static string Romance_Standard_Time_Short {
            get {
                return ResourceManager.GetString("Romance_Standard_Time_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moscow, St. Petersburg, Volgograd (RTZ 2).
        /// </summary>
        internal static string Russian_Standard_Time {
            get {
                return ResourceManager.GetString("Russian_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RTZ2.
        /// </summary>
        internal static string Russian_Standard_Time_Short {
            get {
                return ResourceManager.GetString("Russian_Standard_Time_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chokurdakh (RTZ 10).
        /// </summary>
        internal static string Russia_Time_Zone_10 {
            get {
                return ResourceManager.GetString("Russia_Time_Zone_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RTZ10.
        /// </summary>
        internal static string Russia_Time_Zone_10_Short {
            get {
                return ResourceManager.GetString("Russia_Time_Zone_10_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anadyr, Petropavlovsk-Kamchatsky (RTZ 11).
        /// </summary>
        internal static string Russia_Time_Zone_11 {
            get {
                return ResourceManager.GetString("Russia_Time_Zone_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RTZ11.
        /// </summary>
        internal static string Russia_Time_Zone_11_Short {
            get {
                return ResourceManager.GetString("Russia_Time_Zone_11_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izhevsk, Samara (RTZ 3).
        /// </summary>
        internal static string Russia_Time_Zone_3 {
            get {
                return ResourceManager.GetString("Russia_Time_Zone_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RTZ3.
        /// </summary>
        internal static string Russia_Time_Zone_3_Short {
            get {
                return ResourceManager.GetString("Russia_Time_Zone_3_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samoa.
        /// </summary>
        internal static string Samoa_Standard_Time {
            get {
                return ResourceManager.GetString("Samoa_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMO.
        /// </summary>
        internal static string Samoa_Standard_Time_Short {
            get {
                return ResourceManager.GetString("Samoa_Standard_Time_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cayenne, Fortaleza.
        /// </summary>
        internal static string SA_Eastern_Standard_Time {
            get {
                return ResourceManager.GetString("SA_Eastern_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAET.
        /// </summary>
        internal static string SA_Eastern_Standard_Time_Short {
            get {
                return ResourceManager.GetString("SA_Eastern_Standard_Time_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bogota, Lima, Quito, Rio Branco.
        /// </summary>
        internal static string SA_Pacific_Standard_Time {
            get {
                return ResourceManager.GetString("SA_Pacific_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAPT.
        /// </summary>
        internal static string SA_Pacific_Standard_Time_Short {
            get {
                return ResourceManager.GetString("SA_Pacific_Standard_Time_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Georgetown, La Paz, Manaus, San Juan.
        /// </summary>
        internal static string SA_Western_Standard_Time {
            get {
                return ResourceManager.GetString("SA_Western_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAWT.
        /// </summary>
        internal static string SA_Western_Standard_Time_Short {
            get {
                return ResourceManager.GetString("SA_Western_Standard_Time_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bangkok, Hanoi, Jakarta.
        /// </summary>
        internal static string SE_Asia_Standard_Time {
            get {
                return ResourceManager.GetString("SE_Asia_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SASIA.
        /// </summary>
        internal static string SE_Asia_Standard_Time_Short {
            get {
                return ResourceManager.GetString("SE_Asia_Standard_Time_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kuala Lumpur, Singapore.
        /// </summary>
        internal static string Singapore_Standard_Time {
            get {
                return ResourceManager.GetString("Singapore_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SNGP.
        /// </summary>
        internal static string Singapore_Standard_Time_Short {
            get {
                return ResourceManager.GetString("Singapore_Standard_Time_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harare, Pretoria.
        /// </summary>
        internal static string South_Africa_Standard_Time {
            get {
                return ResourceManager.GetString("South_Africa_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAF.
        /// </summary>
        internal static string South_Africa_Standard_Time_Short {
            get {
                return ResourceManager.GetString("South_Africa_Standard_Time_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sri Jayawardenepura.
        /// </summary>
        internal static string Sri_Lanka_Standard_Time {
            get {
                return ResourceManager.GetString("Sri_Lanka_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SRL.
        /// </summary>
        internal static string Sri_Lanka_Standard_Time_Short {
            get {
                return ResourceManager.GetString("Sri_Lanka_Standard_Time_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damascus.
        /// </summary>
        internal static string Syria_Standard_Time {
            get {
                return ResourceManager.GetString("Syria_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SYR.
        /// </summary>
        internal static string Syria_Standard_Time_Short {
            get {
                return ResourceManager.GetString("Syria_Standard_Time_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taipei.
        /// </summary>
        internal static string Taipei_Standard_Time {
            get {
                return ResourceManager.GetString("Taipei_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAIP.
        /// </summary>
        internal static string Taipei_Standard_Time_Short {
            get {
                return ResourceManager.GetString("Taipei_Standard_Time_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hobart.
        /// </summary>
        internal static string Tasmania_Standard_Time {
            get {
                return ResourceManager.GetString("Tasmania_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TSM.
        /// </summary>
        internal static string Tasmania_Standard_Time_Short {
            get {
                return ResourceManager.GetString("Tasmania_Standard_Time_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Osaka, Sapporo, Tokyo.
        /// </summary>
        internal static string Tokyo_Standard_Time {
            get {
                return ResourceManager.GetString("Tokyo_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TKY.
        /// </summary>
        internal static string Tokyo_Standard_Time_Short {
            get {
                return ResourceManager.GetString("Tokyo_Standard_Time_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuku&apos;alofa.
        /// </summary>
        internal static string Tonga_Standard_Time {
            get {
                return ResourceManager.GetString("Tonga_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TNG.
        /// </summary>
        internal static string Tonga_Standard_Time_Short {
            get {
                return ResourceManager.GetString("Tonga_Standard_Time_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Istanbul.
        /// </summary>
        internal static string Turkey_Standard_Time {
            get {
                return ResourceManager.GetString("Turkey_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TKY.
        /// </summary>
        internal static string Turkey_Standard_Time_Short {
            get {
                return ResourceManager.GetString("Turkey_Standard_Time_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ulaanbaatar.
        /// </summary>
        internal static string Ulaanbaatar_Standard_Time {
            get {
                return ResourceManager.GetString("Ulaanbaatar_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ULNB.
        /// </summary>
        internal static string Ulaanbaatar_Standard_Time_Short {
            get {
                return ResourceManager.GetString("Ulaanbaatar_Standard_Time_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indiana (East).
        /// </summary>
        internal static string US_Eastern_Standard_Time {
            get {
                return ResourceManager.GetString("US_Eastern_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INT.
        /// </summary>
        internal static string US_Eastern_Standard_Time_Short {
            get {
                return ResourceManager.GetString("US_Eastern_Standard_Time_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arizona.
        /// </summary>
        internal static string US_Mountain_Standard_Time {
            get {
                return ResourceManager.GetString("US_Mountain_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AZT.
        /// </summary>
        internal static string US_Mountain_Standard_Time_Short {
            get {
                return ResourceManager.GetString("US_Mountain_Standard_Time_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordinated Universal Time.
        /// </summary>
        internal static string UTC {
            get {
                return ResourceManager.GetString("UTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordinated Universal Time-02.
        /// </summary>
        internal static string UTC02 {
            get {
                return ResourceManager.GetString("UTC02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UTC-2.
        /// </summary>
        internal static string UTC02_Short {
            get {
                return ResourceManager.GetString("UTC02_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordinated Universal Time-11.
        /// </summary>
        internal static string UTC11 {
            get {
                return ResourceManager.GetString("UTC11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UTC-11.
        /// </summary>
        internal static string UTC11_Short {
            get {
                return ResourceManager.GetString("UTC11_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordinated Universal Time+12.
        /// </summary>
        internal static string UTC12 {
            get {
                return ResourceManager.GetString("UTC12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UTC+12.
        /// </summary>
        internal static string UTC12_Short {
            get {
                return ResourceManager.GetString("UTC12_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UTC.
        /// </summary>
        internal static string UTC_Short {
            get {
                return ResourceManager.GetString("UTC_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caracas.
        /// </summary>
        internal static string Venezuela_Standard_Time {
            get {
                return ResourceManager.GetString("Venezuela_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VZT.
        /// </summary>
        internal static string Venezuela_Standard_Time_Short {
            get {
                return ResourceManager.GetString("Venezuela_Standard_Time_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vladivostok, Magadan (RTZ 9).
        /// </summary>
        internal static string Vladivostok_Standard_Time {
            get {
                return ResourceManager.GetString("Vladivostok_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RTZ9.
        /// </summary>
        internal static string Vladivostok_Standard_Time_Short {
            get {
                return ResourceManager.GetString("Vladivostok_Standard_Time_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ashgabat, Tashkent.
        /// </summary>
        internal static string West_Asia_Standard_Time {
            get {
                return ResourceManager.GetString("West_Asia_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WAF.
        /// </summary>
        internal static string West_Asia_Standard_Time_Short {
            get {
                return ResourceManager.GetString("West_Asia_Standard_Time_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guam, Port Moresby.
        /// </summary>
        internal static string West_Pacific_Standard_Time {
            get {
                return ResourceManager.GetString("West_Pacific_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WPAC.
        /// </summary>
        internal static string West_Pacific_Standard_Time_Short {
            get {
                return ResourceManager.GetString("West_Pacific_Standard_Time_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perth.
        /// </summary>
        internal static string W_Australia_Standard_Time {
            get {
                return ResourceManager.GetString("W_Australia_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WAUS.
        /// </summary>
        internal static string W_Australia_Standard_Time_Short {
            get {
                return ResourceManager.GetString("W_Australia_Standard_Time_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to West Central Africa.
        /// </summary>
        internal static string W_Central_Africa_Standard_Time {
            get {
                return ResourceManager.GetString("W_Central_Africa_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WCAT.
        /// </summary>
        internal static string W_Central_Africa_Standard_Time_Short {
            get {
                return ResourceManager.GetString("W_Central_Africa_Standard_Time_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna.
        /// </summary>
        internal static string W_Europe_Standard_Time {
            get {
                return ResourceManager.GetString("W_Europe_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WET.
        /// </summary>
        internal static string W_Europe_Standard_Time_Short {
            get {
                return ResourceManager.GetString("W_Europe_Standard_Time_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yakutsk (RTZ 8).
        /// </summary>
        internal static string Yakutsk_Standard_Time {
            get {
                return ResourceManager.GetString("Yakutsk_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RTZ8.
        /// </summary>
        internal static string Yakutsk_Standard_Time_Short {
            get {
                return ResourceManager.GetString("Yakutsk_Standard_Time_Short", resourceCulture);
            }
        }
    }
}
