//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Validation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Validation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Validation", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must accept Credit Cards in order to offer Instant Checkout.
        /// </summary>
        internal static string AcceptCreditCardRequiredForInstantCheckout {
            get {
                return ResourceManager.GetString("AcceptCreditCardRequiredForInstantCheckout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must accept PayPal or Credit Cards in order to offer Instant Checkout.
        /// </summary>
        internal static string AcceptPayPalOrCreditCardRequiredForInstantCheckout {
            get {
                return ResourceManager.GetString("AcceptPayPalOrCreditCardRequiredForInstantCheckout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must accept PayPal or configure Stripe in order to offer Instant Checkout.
        /// </summary>
        internal static string AcceptPayPalOrStripeRequiredForInstantCheckout {
            get {
                return ResourceManager.GetString("AcceptPayPalOrStripeRequiredForInstantCheckout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must accept PayPal in order to offer Instant Checkout.
        /// </summary>
        internal static string AcceptPayPalRequiredForInstantCheckout {
            get {
                return ResourceManager.GetString("AcceptPayPalRequiredForInstantCheckout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an Address.
        /// </summary>
        internal static string AddressID_Missing {
            get {
                return ResourceManager.GetString("AddressID_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjustment Amount must be a number.
        /// </summary>
        internal static string adjustmentAmount_ConvertDecimal {
            get {
                return ResourceManager.GetString("adjustmentAmount_ConvertDecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjustment Amount must be must greater than zero.
        /// </summary>
        internal static string adjustmentAmount_GTZero {
            get {
                return ResourceManager.GetString("adjustmentAmount_GTZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjustment Amount is required.
        /// </summary>
        internal static string adjustmentAmount_Required {
            get {
                return ResourceManager.GetString("adjustmentAmount_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjustment Description is required.
        /// </summary>
        internal static string adjustmentDescription_Required {
            get {
                return ResourceManager.GetString("adjustmentDescription_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AFieldThatAllItemsHave is required.
        /// </summary>
        internal static string AFieldThatAllItemsHave_Required {
            get {
                return ResourceManager.GetString("AFieldThatAllItemsHave_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount must be a number.
        /// </summary>
        internal static string Amount_ConvertDecimal {
            get {
                return ResourceManager.GetString("Amount_ConvertDecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount must be zero or greater.
        /// </summary>
        internal static string Amount_GTEZero {
            get {
                return ResourceManager.GetString("Amount_GTEZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount must be greater than zero.
        /// </summary>
        internal static string Amount_GTZero {
            get {
                return ResourceManager.GetString("Amount_GTZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount is required.
        /// </summary>
        internal static string Amount_Required {
            get {
                return ResourceManager.GetString("Amount_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer must be between 1 and 250 characters.
        /// </summary>
        internal static string Answer_Length_1_Inclusive_to_250_Inclusive {
            get {
                return ResourceManager.GetString("Answer_Length_1_Inclusive_to_250_Inclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auction changed, please try again.
        /// </summary>
        internal static string AuctionChanged {
            get {
                return ResourceManager.GetString("AuctionChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either &quot;Authorize.NET&quot; or &quot;Stripe&quot; must be disabled.
        /// </summary>
        internal static string AuthNetAndStripeCantBothBeEnabled {
            get {
                return ResourceManager.GetString("AuthNetAndStripeCantBothBeEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must provide Authorize.Net credentials in order to Accept Credit Card Payments.
        /// </summary>
        internal static string AuthNetCredentialsRequiredForAcceptCreditCards {
            get {
                return ResourceManager.GetString("AuthNetCredentialsRequiredForAcceptCreditCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Relist can&apos;t be increased.
        /// </summary>
        internal static string AutoRelistCantBeIncreased {
            get {
                return ResourceManager.GetString("AutoRelistCantBeIncreased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Relist is too high.
        /// </summary>
        internal static string AutoRelistTooHigh {
            get {
                return ResourceManager.GetString("AutoRelistTooHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Relist must be a number.
        /// </summary>
        internal static string AutoRelist_ConvertInteger {
            get {
                return ResourceManager.GetString("AutoRelist_ConvertInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Relist must be greater than or equal to zero.
        /// </summary>
        internal static string AutoRelist_GTZero {
            get {
                return ResourceManager.GetString("AutoRelist_GTZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banner HTML is required.
        /// </summary>
        internal static string BannerHtml_Required {
            get {
                return ResourceManager.GetString("BannerHtml_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A banner image is required.
        /// </summary>
        internal static string BannerMediaId_Required {
            get {
                return ResourceManager.GetString("BannerMediaId_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to convert Time of Day to a Time.
        /// </summary>
        internal static string BatchTime_ConvertDateTime {
            get {
                return ResourceManager.GetString("BatchTime_ConvertDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bid amount is too low.
        /// </summary>
        internal static string BidAmountTooLow {
            get {
                return ResourceManager.GetString("BidAmountTooLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bid Amount must be a number.
        /// </summary>
        internal static string BidAmount_ConvertDecimal {
            get {
                return ResourceManager.GetString("BidAmount_ConvertDecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bid Amount must be greater than zero.
        /// </summary>
        internal static string BidAmount_GTZero {
            get {
                return ResourceManager.GetString("BidAmount_GTZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bid Increment must be a number.
        /// </summary>
        internal static string BidIncrement_ConvertDecimal {
            get {
                return ResourceManager.GetString("BidIncrement_ConvertDecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bid Increment must be must be greater than zero.
        /// </summary>
        internal static string BidIncrement_GTZero {
            get {
                return ResourceManager.GetString("BidIncrement_GTZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to convert Birthday to a Date/Time.
        /// </summary>
        internal static string Birthday_ConvertDateTime {
            get {
                return ResourceManager.GetString("Birthday_ConvertDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday is required.
        /// </summary>
        internal static string Birthday_Required {
            get {
                return ResourceManager.GetString("Birthday_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body is required.
        /// </summary>
        internal static string Body_Length_1_Inclusive_to_0_Ignore {
            get {
                return ResourceManager.GetString("Body_Length_1_Inclusive_to_0_Ignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body must be between 3 and 100,000 characters.
        /// </summary>
        internal static string Body_Length_3_Inclusive_to_100000_Inclusive {
            get {
                return ResourceManager.GetString("Body_Length_3_Inclusive_to_100000_Inclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Buyers Premium Percentage.
        /// </summary>
        internal static string BuyersPremiumPercent_ConvertDecimal {
            get {
                return ResourceManager.GetString("BuyersPremiumPercent_ConvertDecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Buyers Premium Percentage.
        /// </summary>
        internal static string BuyersPremiumPercent_InvalidPercentageValue {
            get {
                return ResourceManager.GetString("BuyersPremiumPercent_InvalidPercentageValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry.  This listing is no longer eligible for instant purchase.  Please feel free to enter your BID below..
        /// </summary>
        internal static string BuyNowNotAvailable {
            get {
                return ResourceManager.GetString("BuyNowNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The shipping method could not be deleted because it is referenced by one or more listings.
        /// </summary>
        internal static string CantDeleteShippingMethod {
            get {
                return ResourceManager.GetString("CantDeleteShippingMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Failure:  Cannot send message to self..
        /// </summary>
        internal static string CantSendMessageToSelf {
            get {
                return ResourceManager.GetString("CantSendMessageToSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Number appears to be invalid.
        /// </summary>
        internal static string CardNumber_AlgorithmInvalid {
            get {
                return ResourceManager.GetString("CardNumber_AlgorithmInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Number is not in the correct format.
        /// </summary>
        internal static string CardNumber_FormatInvalid {
            get {
                return ResourceManager.GetString("CardNumber_FormatInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Number is required.
        /// </summary>
        internal static string CardNumber_Required {
            get {
                return ResourceManager.GetString("CardNumber_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Type is required.
        /// </summary>
        internal static string CardType_Required {
            get {
                return ResourceManager.GetString("CardType_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Category ID.
        /// </summary>
        internal static string CategoryIDMissing {
            get {
                return ResourceManager.GetString("CategoryIDMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City must be at least 1 character.
        /// </summary>
        internal static string City_Length_1_Inclusive_to_0_Ignore {
            get {
                return ResourceManager.GetString("City_Length_1_Inclusive_to_0_Ignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City must contain between 1 and 200 characters.
        /// </summary>
        internal static string City_Length_1_Inclusive_to_200_Inclusive {
            get {
                return ResourceManager.GetString("City_Length_1_Inclusive_to_200_Inclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listing changed, please try again.
        /// </summary>
        internal static string ClassifiedChanged {
            get {
                return ResourceManager.GetString("ClassifiedChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing Group Increment change not allowed for this event.
        /// </summary>
        internal static string ClosingGroupIncrementChangeNotAllowed {
            get {
                return ResourceManager.GetString("ClosingGroupIncrementChangeNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing Group Increment must be a whole number.
        /// </summary>
        internal static string ClosingGroupIncrementSeconds_ConvertInteger {
            get {
                return ResourceManager.GetString("ClosingGroupIncrementSeconds_ConvertInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing Group Increment is required.
        /// </summary>
        internal static string ClosingGroupIncrementSeconds_Required {
            get {
                return ResourceManager.GetString("ClosingGroupIncrementSeconds_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment must be between 3 and 80 characters.
        /// </summary>
        internal static string Comment_Length_3_Inclusive_to_80_Inclusive {
            get {
                return ResourceManager.GetString("Comment_Length_3_Inclusive_to_80_Inclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment is required.
        /// </summary>
        internal static string Comment_Required {
            get {
                return ResourceManager.GetString("Comment_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The confirmation email doesn&apos;t match the email address.
        /// </summary>
        internal static string ConfirmationEmailMismatch {
            get {
                return ResourceManager.GetString("ConfirmationEmailMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password and confirmation password do not match..
        /// </summary>
        internal static string ConfirmationNewPasswordMismatch {
            get {
                return ResourceManager.GetString("ConfirmationNewPasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The confirmation password doesn&apos;t match the password.
        /// </summary>
        internal static string ConfirmationPasswordMismatch {
            get {
                return ResourceManager.GetString("ConfirmationPasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation email is required.
        /// </summary>
        internal static string confirmEmail_Required {
            get {
                return ResourceManager.GetString("confirmEmail_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password is required.
        /// </summary>
        internal static string confirmPassword_Required {
            get {
                return ResourceManager.GetString("confirmPassword_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Name Already Exists.
        /// </summary>
        internal static string ContentNameAlreadyExists {
            get {
                return ResourceManager.GetString("ContentNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country does not exist.
        /// </summary>
        internal static string CountryNotExist {
            get {
                return ResourceManager.GetString("CountryNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country is required.
        /// </summary>
        internal static string Country_Required {
            get {
                return ResourceManager.GetString("Country_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Card Required.
        /// </summary>
        internal static string CreditCardRequired {
            get {
                return ResourceManager.GetString("CreditCardRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Card is expired.
        /// </summary>
        internal static string CreditCard_Expired {
            get {
                return ResourceManager.GetString("CreditCard_Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Culture Management Success.
        /// </summary>
        internal static string CultureManagementSuccess {
            get {
                return ResourceManager.GetString("CultureManagementSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password is incorrect.
        /// </summary>
        internal static string CurrenctPasswordIncorrect {
            get {
                return ResourceManager.GetString("CurrenctPasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The custom field you are trying to add already exists.
        /// </summary>
        internal static string CustomFieldAlreadyExists {
            get {
                return ResourceManager.GetString("CustomFieldAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Field Names must be 100 characters or less.
        /// </summary>
        internal static string CustomFieldNameTooLong {
            get {
                return ResourceManager.GetString("CustomFieldNameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field you are trying to add is a reserved word and cannot be used..
        /// </summary>
        internal static string CustomFieldReservedWord {
            get {
                return ResourceManager.GetString("CustomFieldReservedWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be a comma delimited list of whole numbers.
        /// </summary>
        internal static string CustomField_CommaListInts {
            get {
                return ResourceManager.GetString("CustomField_CommaListInts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be true or false.
        /// </summary>
        internal static string CustomField_ConvertBoolean {
            get {
                return ResourceManager.GetString("CustomField_ConvertBoolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be a valid date.
        /// </summary>
        internal static string CustomField_ConvertDateTime {
            get {
                return ResourceManager.GetString("CustomField_ConvertDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be a number.
        /// </summary>
        internal static string CustomField_ConvertDecimal {
            get {
                return ResourceManager.GetString("CustomField_ConvertDecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be a number.
        /// </summary>
        internal static string CustomField_ConvertInteger {
            get {
                return ResourceManager.GetString("CustomField_ConvertInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing {0} is not allowed.
        /// </summary>
        internal static string CustomField_EditNotAllowed {
            get {
                return ResourceManager.GetString("CustomField_EditNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be greater than zero.
        /// </summary>
        internal static string CustomField_GTZero {
            get {
                return ResourceManager.GetString("CustomField_GTZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not one of the allowed values.
        /// </summary>
        internal static string CustomField_InvalidValue {
            get {
                return ResourceManager.GetString("CustomField_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is too long.
        /// </summary>
        internal static string CustomField_MaxLength {
            get {
                return ResourceManager.GetString("CustomField_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is too short.
        /// </summary>
        internal static string CustomField_MinLength {
            get {
                return ResourceManager.GetString("CustomField_MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required.
        /// </summary>
        internal static string CustomField_Missing {
            get {
                return ResourceManager.GetString("CustomField_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be negative.
        /// </summary>
        internal static string CustomField_NonNegative {
            get {
                return ResourceManager.GetString("CustomField_NonNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required.
        /// </summary>
        internal static string CustomField_Required {
            get {
                return ResourceManager.GetString("CustomField_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is too low.
        /// </summary>
        internal static string CustomField_TooLow {
            get {
                return ResourceManager.GetString("CustomField_TooLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Listings Days Old must be  zero or greater.
        /// </summary>
        internal static string DataCleanup_DeleteListings_DaysOld_GTEZero {
            get {
                return ResourceManager.GetString("DataCleanup_DeleteListings_DaysOld_GTEZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Value must be true or false.
        /// </summary>
        internal static string Default_ConvertBoolean {
            get {
                return ResourceManager.GetString("Default_ConvertBoolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Value must be a valid date.
        /// </summary>
        internal static string Default_ConvertDateTime {
            get {
                return ResourceManager.GetString("Default_ConvertDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Value must be a number.
        /// </summary>
        internal static string Default_ConvertDecimal {
            get {
                return ResourceManager.GetString("Default_ConvertDecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Value must be a number.
        /// </summary>
        internal static string Default_ConvertInteger {
            get {
                return ResourceManager.GetString("Default_ConvertInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested changes were not been saved because the site is in demo mode..
        /// </summary>
        internal static string DemoDisabledNotSaved {
            get {
                return ResourceManager.GetString("DemoDisabledNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Description_Length_0_Ignore_to_1000_Inclusive {
            get {
                return ResourceManager.GetString("Description_Length_0_Ignore_to_1000_Inclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description must be at least 1 character.
        /// </summary>
        internal static string Description_Length_1_Inclusive_to_0_Ignore {
            get {
                return ResourceManager.GetString("Description_Length_1_Inclusive_to_0_Ignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Description_Length_1_Inclusive_to_1_Ignore {
            get {
                return ResourceManager.GetString("Description_Length_1_Inclusive_to_1_Ignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description must be between 1 and 200 characters.
        /// </summary>
        internal static string Description_Length_1_Inclusive_to_200_Inclusive {
            get {
                return ResourceManager.GetString("Description_Length_1_Inclusive_to_200_Inclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description must be between 3 and 200 characters.
        /// </summary>
        internal static string Description_Length_3_Inclusive_to_200_Inclusive {
            get {
                return ResourceManager.GetString("Description_Length_3_Inclusive_to_200_Inclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description is required.
        /// </summary>
        internal static string Description_Required {
            get {
                return ResourceManager.GetString("Description_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Order must be a number.
        /// </summary>
        internal static string DisplayOrder_ConvertInteger {
            get {
                return ResourceManager.GetString("DisplayOrder_ConvertInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Order is required.
        /// </summary>
        internal static string DisplayOrder_Required {
            get {
                return ResourceManager.GetString("DisplayOrder_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Shipping Method.
        /// </summary>
        internal static string DuplicateShippingMethod {
            get {
                return ResourceManager.GetString("DuplicateShippingMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration is required.
        /// </summary>
        internal static string Duration_Required {
            get {
                return ResourceManager.GetString("Duration_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address already exists.
        /// </summary>
        internal static string Email_Exists {
            get {
                return ResourceManager.GetString("Email_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address appears to be invalid.
        /// </summary>
        internal static string Email_Invalid {
            get {
                return ResourceManager.GetString("Email_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address does not meet the character limits.
        /// </summary>
        internal static string Email_Length_3_Inclusive_to_500_Inclusive {
            get {
                return ResourceManager.GetString("Email_Length_3_Inclusive_to_500_Inclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address is required.
        /// </summary>
        internal static string Email_Required {
            get {
                return ResourceManager.GetString("Email_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date change not allowed for this event.
        /// </summary>
        internal static string EndDateChangeNotAllowed {
            get {
                return ResourceManager.GetString("EndDateChangeNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date/Time must be in the future.
        /// </summary>
        internal static string EndDateTimeMustBeInTheFuture {
            get {
                return ResourceManager.GetString("EndDateTimeMustBeInTheFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date must be a valid date value.
        /// </summary>
        internal static string EndDate_ConvertDateTime {
            get {
                return ResourceManager.GetString("EndDate_ConvertDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ending Date is required.
        /// </summary>
        internal static string EndDate_Required {
            get {
                return ResourceManager.GetString("EndDate_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date/Time must be after Start Date/Time.
        /// </summary>
        internal static string EndDTTMBeforeStartDTTM {
            get {
                return ResourceManager.GetString("EndDTTMBeforeStartDTTM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Time must be a valid time value.
        /// </summary>
        internal static string EndTime_ConvertDateTime {
            get {
                return ResourceManager.GetString("EndTime_ConvertDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ending Time is required.
        /// </summary>
        internal static string EndTime_Required {
            get {
                return ResourceManager.GetString("EndTime_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description is required.
        /// </summary>
        internal static string EventDescription_Required {
            get {
                return ResourceManager.GetString("EventDescription_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration Month must be an integer between 1 and 12.
        /// </summary>
        internal static string ExpirationMonth_Range_1_Inclusive_to_12_Inclusive {
            get {
                return ResourceManager.GetString("ExpirationMonth_Range_1_Inclusive_to_12_Inclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration Month is required.
        /// </summary>
        internal static string ExpirationMonth_Required {
            get {
                return ResourceManager.GetString("ExpirationMonth_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration Year is invalid..
        /// </summary>
        internal static string ExpirationYear_Range_2010_Inclusive_to_2070_Inclusive {
            get {
                return ResourceManager.GetString("ExpirationYear_Range_2010_Inclusive_to_2070_Inclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration Year is required.
        /// </summary>
        internal static string ExpirationYear_Required {
            get {
                return ResourceManager.GetString("ExpirationYear_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field does not exist.
        /// </summary>
        internal static string FieldNotExist {
            get {
                return ResourceManager.GetString("FieldNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name must be at least 1 character.
        /// </summary>
        internal static string FirstName_Length_1_Inclusive_to_0_Ignore {
            get {
                return ResourceManager.GetString("FirstName_Length_1_Inclusive_to_0_Ignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name must be less than 200 characters.
        /// </summary>
        internal static string FirstName_Length_1_Inclusive_to_200_Inclusive {
            get {
                return ResourceManager.GetString("FirstName_Length_1_Inclusive_to_200_Inclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name is required.
        /// </summary>
        internal static string FirstName_Required {
            get {
                return ResourceManager.GetString("FirstName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listing changed, please try again.
        /// </summary>
        internal static string FixedPriceChanged {
            get {
                return ResourceManager.GetString("FixedPriceChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed Price must be a number.
        /// </summary>
        internal static string FixedPrice_ConvertDecimal {
            get {
                return ResourceManager.GetString("FixedPrice_ConvertDecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy Now Price is too low.
        /// </summary>
        internal static string FixedPrice_TooLow {
            get {
                return ResourceManager.GetString("FixedPrice_TooLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format String is required.
        /// </summary>
        internal static string FormatString_Required {
            get {
                return ResourceManager.GetString("FormatString_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enable at least one language..
        /// </summary>
        internal static string IllegalNoLanguages {
            get {
                return ResourceManager.GetString("IllegalNoLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The default site culture is related to one of the languages you attempted to disable.  Change the default site culture to match an enabled language first..
        /// </summary>
        internal static string IllegalSiteCultureForLanguages {
            get {
                return ResourceManager.GetString("IllegalSiteCultureForLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount must be greater than zero.
        /// </summary>
        internal static string IncrementAmountMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("IncrementAmountMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Level must be zero or greater.
        /// </summary>
        internal static string IncrementPriceLevelMustBeZeroOrGreater {
            get {
                return ResourceManager.GetString("IncrementPriceLevelMustBeZeroOrGreater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more Increment values (under Increments) contains data that cannot be converted to a decimal..
        /// </summary>
        internal static string INC_Increment_ConvertDecimal {
            get {
                return ResourceManager.GetString("INC_Increment_ConvertDecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more Increment values (under Increments) is less than 0.01.  All Increment values must be &gt;= 0.01.
        /// </summary>
        internal static string INC_Increment_GTZero {
            get {
                return ResourceManager.GetString("INC_Increment_GTZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more Price Level values (under Increments) contains data that cannot be converted to a decimal..
        /// </summary>
        internal static string INC_PriceLevel_ConvertDecimal {
            get {
                return ResourceManager.GetString("INC_PriceLevel_ConvertDecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more Price Level values (under Increments) is less than zero.  All Price Level values must be &gt;= zero.
        /// </summary>
        internal static string INC_PriceLevel_GTZero {
            get {
                return ResourceManager.GetString("INC_PriceLevel_GTZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Display Order.
        /// </summary>
        internal static string InvalidDisplayOrderValue {
            get {
                return ResourceManager.GetString("InvalidDisplayOrderValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Shipping Method Name.
        /// </summary>
        internal static string InvalidShippingMethodName {
            get {
                return ResourceManager.GetString("InvalidShippingMethodName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Time Zone.
        /// </summary>
        internal static string InvalidTimeZone {
            get {
                return ResourceManager.GetString("InvalidTimeZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CAPTCHA code is missing or invalid.
        /// </summary>
        internal static string Invalid_Captcha {
            get {
                return ResourceManager.GetString("Invalid_Captcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice # must be a number.
        /// </summary>
        internal static string InvoiceNumber_ConvertInteger {
            get {
                return ResourceManager.GetString("InvoiceNumber_ConvertInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name must be at least 1 character.
        /// </summary>
        internal static string LastName_Length_1_Inclusive_to_0_Ignore {
            get {
                return ResourceManager.GetString("LastName_Length_1_Inclusive_to_0_Ignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name must be less than 200 characters.
        /// </summary>
        internal static string LastName_Length_1_Inclusive_to_200_Inclusive {
            get {
                return ResourceManager.GetString("LastName_Length_1_Inclusive_to_200_Inclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name is required.
        /// </summary>
        internal static string LastName_Required {
            get {
                return ResourceManager.GetString("LastName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a category that does not have any sub-categories.
        /// </summary>
        internal static string LeafCategoryRequired {
            get {
                return ResourceManager.GetString("LeafCategoryRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Licence is invalid.  Contact the site administrator for further information..
        /// </summary>
        internal static string LicenceInvalid {
            get {
                return ResourceManager.GetString("LicenceInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A banner link is required.
        /// </summary>
        internal static string LinkURI_Required {
            get {
                return ResourceManager.GetString("LinkURI_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Listing ID.
        /// </summary>
        internal static string ListingIDMissing {
            get {
                return ResourceManager.GetString("ListingIDMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listing ID must be a number.
        /// </summary>
        internal static string ListingId_ConvertInteger {
            get {
                return ResourceManager.GetString("ListingId_ConvertInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listing ID is Missing.
        /// </summary>
        internal static string ListingId_Missing {
            get {
                return ResourceManager.GetString("ListingId_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listing not found.
        /// </summary>
        internal static string ListingNotFound {
            get {
                return ResourceManager.GetString("ListingNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listing # must be a number.
        /// </summary>
        internal static string ListingNumber_ConvertInteger {
            get {
                return ResourceManager.GetString("ListingNumber_ConvertInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listing Type Not Specified.
        /// </summary>
        internal static string ListingTypeNotSpecified {
            get {
                return ResourceManager.GetString("ListingTypeNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Failed, User Name or Password is incorrect.
        /// </summary>
        internal static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lot not found.
        /// </summary>
        internal static string LotNotFound {
            get {
                return ResourceManager.GetString("LotNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lot Number must be unique.
        /// </summary>
        internal static string LotNumber_Exists {
            get {
                return ResourceManager.GetString("LotNumber_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lot Number is required.
        /// </summary>
        internal static string LotNumber_Required {
            get {
                return ResourceManager.GetString("LotNumber_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lower Bound must be a number.
        /// </summary>
        internal static string LowerBoundInclusive_ConvertDecimal {
            get {
                return ResourceManager.GetString("LowerBoundInclusive_ConvertDecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lower Bound must be zero or greater.
        /// </summary>
        internal static string LowerBoundInclusive_GTEZero {
            get {
                return ResourceManager.GetString("LowerBoundInclusive_GTEZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lower Bound is required.
        /// </summary>
        internal static string LowerBoundInclusive_Required {
            get {
                return ResourceManager.GetString("LowerBoundInclusive_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Managed By must be 1000 characters or less.
        /// </summary>
        internal static string ManagedByName_Length_0_Inclusive_to_1000_Inclusive {
            get {
                return ResourceManager.GetString("ManagedByName_Length_0_Inclusive_to_1000_Inclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have exceeded the maximum number of images..
        /// </summary>
        internal static string MaxImagesExceeded {
            get {
                return ResourceManager.GetString("MaxImagesExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Results Per Page must be greater than zero.
        /// </summary>
        internal static string MaxResultsPerPage_GTZero {
            get {
                return ResourceManager.GetString("MaxResultsPerPage_GTZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message is required.
        /// </summary>
        internal static string Message_Required {
            get {
                return ResourceManager.GetString("Message_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes must be a number.
        /// </summary>
        internal static string Minutes_ConvertInteger {
            get {
                return ResourceManager.GetString("Minutes_ConvertInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes must be greater than zero.
        /// </summary>
        internal static string Minutes_GTZero {
            get {
                return ResourceManager.GetString("Minutes_GTZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes is required.
        /// </summary>
        internal static string Minutes_Required {
            get {
                return ResourceManager.GetString("Minutes_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing payment provider for IPN.
        /// </summary>
        internal static string MissingPaymentProviderForIPN {
            get {
                return ResourceManager.GetString("MissingPaymentProviderForIPN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A bid increment with a price level of 0 is required.
        /// </summary>
        internal static string MissingZeroLevelIncrement {
            get {
                return ResourceManager.GetString("MissingZeroLevelIncrement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must accept the Terms &amp; Conditions to complete your registration.
        /// </summary>
        internal static string MustAgreeToAgreements {
            get {
                return ResourceManager.GetString("MustAgreeToAgreements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Name may only contain alpha numeric characters, dashes, underscores or periods.
        /// </summary>
        internal static string Name_Invalid {
            get {
                return ResourceManager.GetString("Name_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Name must be less than 200 characters.
        /// </summary>
        internal static string Name_Length_1_Ignore_to_200_Inclusive {
            get {
                return ResourceManager.GetString("Name_Length_1_Ignore_to_200_Inclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Name is required.
        /// </summary>
        internal static string Name_Length_1_Inclusive_to_200_Ignore {
            get {
                return ResourceManager.GetString("Name_Length_1_Inclusive_to_200_Ignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required.
        /// </summary>
        internal static string Name_Required {
            get {
                return ResourceManager.GetString("Name_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Field names may only contain letters, numbers, spaces, and underscores..
        /// </summary>
        internal static string NewCustomField_Name_Invalid {
            get {
                return ResourceManager.GetString("NewCustomField_Name_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No valid State/Region data was found.  Each line must contain the State/Region Code, followed by a comma, followed by the State/Region Name..
        /// </summary>
        internal static string NoValidStateDataFound {
            get {
                return ResourceManager.GetString("NoValidStateDataFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer Already Accepted.
        /// </summary>
        internal static string OfferAlreadyAccepted {
            get {
                return ResourceManager.GetString("OfferAlreadyAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer Amount must be less than the Buy Now price.
        /// </summary>
        internal static string OfferAmountMustBeLessThanBuyNowPrice {
            get {
                return ResourceManager.GetString("OfferAmountMustBeLessThanBuyNowPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer Amount must be less than the price.
        /// </summary>
        internal static string OfferAmountMustBeLessThanPrice {
            get {
                return ResourceManager.GetString("OfferAmountMustBeLessThanPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer Message must be 250 characters or less.
        /// </summary>
        internal static string OfferMessage_Length_0_Ignore_to_250_Inclusive {
            get {
                return ResourceManager.GetString("OfferMessage_Length_0_Ignore_to_250_Inclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer not found.
        /// </summary>
        internal static string OfferNotFound {
            get {
                return ResourceManager.GetString("OfferNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Since you supplied a Password Answer, Password Question is required.
        /// </summary>
        internal static string PasswordAnswerRequiresPasswordQuestion {
            get {
                return ResourceManager.GetString("PasswordAnswerRequiresPasswordQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required.
        /// </summary>
        internal static string PasswordMissing {
            get {
                return ResourceManager.GetString("PasswordMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Since you supplied a Password Question, Password Answer is required.
        /// </summary>
        internal static string PasswordQuestionRequiresPasswordAnswer {
            get {
                return ResourceManager.GetString("PasswordQuestionRequiresPasswordAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords must have at least one digit (&apos;0&apos;-&apos;9&apos;)..
        /// </summary>
        internal static string PasswordRequireDigit {
            get {
                return ResourceManager.GetString("PasswordRequireDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords must have at least one lowercase (&apos;a&apos;-&apos;z&apos;)..
        /// </summary>
        internal static string PasswordRequireLower {
            get {
                return ResourceManager.GetString("PasswordRequireLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords must have at least one non letter or digit character..
        /// </summary>
        internal static string PasswordRequireNonLetterOrDigit {
            get {
                return ResourceManager.GetString("PasswordRequireNonLetterOrDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords must have at least one uppercase (&apos;A&apos;-&apos;Z&apos;)..
        /// </summary>
        internal static string PasswordRequireUpper {
            get {
                return ResourceManager.GetString("PasswordRequireUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords must be at least {0} characters..
        /// </summary>
        internal static string PasswordTooShort {
            get {
                return ResourceManager.GetString("PasswordTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be between 6 and 100 characters.
        /// </summary>
        internal static string Password_Length_6_Inclusive_to_100_Inclusive {
            get {
                return ResourceManager.GetString("Password_Length_6_Inclusive_to_100_Inclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required.
        /// </summary>
        internal static string Password_Required {
            get {
                return ResourceManager.GetString("Password_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must provide a PayPal Email in order to set Accept PayPal Payments.
        /// </summary>
        internal static string PayPalEmailRequiredForAcceptPayPal {
            get {
                return ResourceManager.GetString("PayPalEmailRequiredForAcceptPayPal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PayPal Email address appears to be invalid.
        /// </summary>
        internal static string PayPal_Email_Invalid {
            get {
                return ResourceManager.GetString("PayPal_Email_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price High must be a number.
        /// </summary>
        internal static string PriceHigh_ConvertDecimal {
            get {
                return ResourceManager.GetString("PriceHigh_ConvertDecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Level must be a number.
        /// </summary>
        internal static string PriceLevel_ConvertDecimal {
            get {
                return ResourceManager.GetString("PriceLevel_ConvertDecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Level must be must greater than zero.
        /// </summary>
        internal static string PriceLevel_GTZero {
            get {
                return ResourceManager.GetString("PriceLevel_GTZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Low must be a number.
        /// </summary>
        internal static string PriceLow_ConvertDecimal {
            get {
                return ResourceManager.GetString("PriceLow_ConvertDecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price must be a number.
        /// </summary>
        internal static string Price_ConvertDecimal {
            get {
                return ResourceManager.GetString("Price_ConvertDecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price must be greater than zero.
        /// </summary>
        internal static string Price_GTZero {
            get {
                return ResourceManager.GetString("Price_GTZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price is required.
        /// </summary>
        internal static string Price_Required {
            get {
                return ResourceManager.GetString("Price_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity must be a number equal to or less than the number available.
        /// </summary>
        internal static string QuantityTooHigh {
            get {
                return ResourceManager.GetString("QuantityTooHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity must be a number equal to or less than the number available.
        /// </summary>
        internal static string Quantity_ConvertInteger {
            get {
                return ResourceManager.GetString("Quantity_ConvertInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity must be greater than zero.
        /// </summary>
        internal static string Quantity_GTZero {
            get {
                return ResourceManager.GetString("Quantity_GTZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity is required.
        /// </summary>
        internal static string Quantity_Required {
            get {
                return ResourceManager.GetString("Quantity_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question must be between 1 and 250 characters.
        /// </summary>
        internal static string Question_Length_1_Inclusive_to_250_Inclusive {
            get {
                return ResourceManager.GetString("Question_Length_1_Inclusive_to_250_Inclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating is required.
        /// </summary>
        internal static string Rating_Missing {
            get {
                return ResourceManager.GetString("Rating_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating is required.
        /// </summary>
        internal static string Rating_Required {
            get {
                return ResourceManager.GetString("Rating_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recaptcha Private Key is required in order to Enable Recaptcha For Contact Us.
        /// </summary>
        internal static string RecaptchaPrivateKey_Required_For_EnableRecaptchaForContactUs {
            get {
                return ResourceManager.GetString("RecaptchaPrivateKey_Required_For_EnableRecaptchaForContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recaptcha Private Key is required in order to Enable Recaptcha For Registration.
        /// </summary>
        internal static string RecaptchaPrivateKey_Required_For_EnableRecaptchaForRegistration {
            get {
                return ResourceManager.GetString("RecaptchaPrivateKey_Required_For_EnableRecaptchaForRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recaptcha Public Key is required in order to Enable Recaptcha For Contact Us.
        /// </summary>
        internal static string RecaptchaPublicKey_Required_For_EnableRecaptchaForContactUs {
            get {
                return ResourceManager.GetString("RecaptchaPublicKey_Required_For_EnableRecaptchaForContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recaptcha Public Key is required in order to Enable Recaptcha For Registration.
        /// </summary>
        internal static string RecaptchaPublicKey_Required_For_EnableRecaptchaForRegistration {
            get {
                return ResourceManager.GetString("RecaptchaPublicKey_Required_For_EnableRecaptchaForRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin-only User fields cannot be set to required and not deferred..
        /// </summary>
        internal static string RequiredNonDeferredAdminOnlyUserFieldNotAllowed {
            get {
                return ResourceManager.GetString("RequiredNonDeferredAdminOnlyUserFieldNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserve Price must be a number.
        /// </summary>
        internal static string ReservePrice_ConvertDecimal {
            get {
                return ResourceManager.GetString("ReservePrice_ConvertDecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserve Price is too low.
        /// </summary>
        internal static string ReservePrice_TooLow {
            get {
                return ResourceManager.GetString("ReservePrice_TooLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Category and Listing Type.
        /// </summary>
        internal static string SelectCategoryAndListingType {
            get {
                return ResourceManager.GetString("SelectCategoryAndListingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping Amount must be numeric.
        /// </summary>
        internal static string shippingAmountNotNumeric {
            get {
                return ResourceManager.GetString("shippingAmountNotNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping Info is required.
        /// </summary>
        internal static string ShippingInfo_Required {
            get {
                return ResourceManager.GetString("ShippingInfo_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Extend Increment must be a whole number.
        /// </summary>
        internal static string SoftClosingGroupIncrementSeconds_ConvertInteger {
            get {
                return ResourceManager.GetString("SoftClosingGroupIncrementSeconds_ConvertInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Extend Increment is required.
        /// </summary>
        internal static string SoftClosingGroupIncrementSeconds_Required {
            get {
                return ResourceManager.GetString("SoftClosingGroupIncrementSeconds_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date change not allowed for this event.
        /// </summary>
        internal static string StartDateChangeNotAllowed {
            get {
                return ResourceManager.GetString("StartDateChangeNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date must be a valid date value.
        /// </summary>
        internal static string StartDate_ConvertDateTime {
            get {
                return ResourceManager.GetString("StartDate_ConvertDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Date is required.
        /// </summary>
        internal static string StartDate_Required {
            get {
                return ResourceManager.GetString("StartDate_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time must be a valid time value.
        /// </summary>
        internal static string StartTime_ConvertDateTime {
            get {
                return ResourceManager.GetString("StartTime_ConvertDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Time is required.
        /// </summary>
        internal static string StartTime_Required {
            get {
                return ResourceManager.GetString("StartTime_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State/Region Codes under the same country must be unique.
        /// </summary>
        internal static string StateCodesMustBeUnique {
            get {
                return ResourceManager.GetString("StateCodesMustBeUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State/Region must be at least 1 character.
        /// </summary>
        internal static string StateRegion_Length_1_Inclusive_to_0_Ignore {
            get {
                return ResourceManager.GetString("StateRegion_Length_1_Inclusive_to_0_Ignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State/Region is required.
        /// </summary>
        internal static string StateRegion_Length_1_Inclusive_to_200_Inclusive {
            get {
                return ResourceManager.GetString("StateRegion_Length_1_Inclusive_to_200_Inclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State/Region Code must be between 1 and 10 characters.
        /// </summary>
        internal static string State_Code_Length_1_Inclusive_to_10_Inclusive {
            get {
                return ResourceManager.GetString("State_Code_Length_1_Inclusive_to_10_Inclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State/Region Name must be between 1 and 100 characters.
        /// </summary>
        internal static string State_Name_Length_1_Inclusive_to_100_Inclusive {
            get {
                return ResourceManager.GetString("State_Name_Length_1_Inclusive_to_100_Inclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When Stripe is enabled, Stored Credit Cards must be disabled.
        /// </summary>
        internal static string StoredCreditCardsAndStripeCantBothBeEnabled {
            get {
                return ResourceManager.GetString("StoredCreditCardsAndStripeCantBothBeEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street Line 1 must be at least 1 character.
        /// </summary>
        internal static string Street1_Length_1_Inclusive_to_0_Ignore {
            get {
                return ResourceManager.GetString("Street1_Length_1_Inclusive_to_0_Ignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street Line 1 must be between 1 and 200 characters.
        /// </summary>
        internal static string Street1_Length_1_Inclusive_to_200_Inclusive {
            get {
                return ResourceManager.GetString("Street1_Length_1_Inclusive_to_200_Inclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must connect your Stripe.com account in order to Accept Credit Card Payments.
        /// </summary>
        internal static string StripeConnectCredentialsRequiredForAcceptCreditCards {
            get {
                return ResourceManager.GetString("StripeConnectCredentialsRequiredForAcceptCreditCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must configure Stripe in order to offer Instant Checkout.
        /// </summary>
        internal static string StripeRequiredForInstantCheckout {
            get {
                return ResourceManager.GetString("StripeRequiredForInstantCheckout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject is required, up to 500 characters.
        /// </summary>
        internal static string Subject_Length_1_Inclusive_to_500_Inclusive {
            get {
                return ResourceManager.GetString("Subject_Length_1_Inclusive_to_500_Inclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject must be between 3 and 100 characters.
        /// </summary>
        internal static string Subject_Length_3_Inclusive_to_100_Inclusive {
            get {
                return ResourceManager.GetString("Subject_Length_3_Inclusive_to_100_Inclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary must be 1000 characters or less.
        /// </summary>
        internal static string Subtitle_Length_0_Inclusive_to_1000_Inclusive {
            get {
                return ResourceManager.GetString("Subtitle_Length_0_Inclusive_to_1000_Inclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email template does not exist.
        /// </summary>
        internal static string TemplateNotExist {
            get {
                return ResourceManager.GetString("TemplateNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms &amp; Conditions are required.
        /// </summary>
        internal static string TermsAndConditions_Required {
            get {
                return ResourceManager.GetString("TermsAndConditions_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title must be 1000 characters or less.
        /// </summary>
        internal static string Title_Length_1_Inclusive_to_1000_Inclusive {
            get {
                return ResourceManager.GetString("Title_Length_1_Inclusive_to_1000_Inclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title must be 200 characters or less.
        /// </summary>
        internal static string Title_Length_1_Inclusive_to_200_Inclusive {
            get {
                return ResourceManager.GetString("Title_Length_1_Inclusive_to_200_Inclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title must be 80 characters or less.
        /// </summary>
        internal static string Title_Length_1_Inclusive_to_80_Inclusive {
            get {
                return ResourceManager.GetString("Title_Length_1_Inclusive_to_80_Inclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title is required.
        /// </summary>
        internal static string Title_Required {
            get {
                return ResourceManager.GetString("Title_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown billing country &apos;{0}&apos;.
        /// </summary>
        internal static string UnknownBillingCountryX {
            get {
                return ResourceManager.GetString("UnknownBillingCountryX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown country &apos;{0}&apos;.
        /// </summary>
        internal static string UnknownCountryX {
            get {
                return ResourceManager.GetString("UnknownCountryX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upper Bound must be a number.
        /// </summary>
        internal static string UpperBoundExclusive_ConvertDecimal {
            get {
                return ResourceManager.GetString("UpperBoundExclusive_ConvertDecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upper Bound must be zero or greater.
        /// </summary>
        internal static string UpperBoundExclusive_GTEZero {
            get {
                return ResourceManager.GetString("UpperBoundExclusive_GTEZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upper Bound is required.
        /// </summary>
        internal static string UpperBoundExclusive_Required {
            get {
                return ResourceManager.GetString("UpperBoundExclusive_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is locked.  Please contact the site administrator..
        /// </summary>
        internal static string UserIsLockedOut {
            get {
                return ResourceManager.GetString("UserIsLockedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has not been approved yet..
        /// </summary>
        internal static string UserIsNotApproved {
            get {
                return ResourceManager.GetString("UserIsNotApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has not been verified.  Please check your email and follow the instructions..
        /// </summary>
        internal static string UserIsNotVerified {
            get {
                return ResourceManager.GetString("UserIsNotVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is required.
        /// </summary>
        internal static string UserNameMissing {
            get {
                return ResourceManager.GetString("UserNameMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username already exists.
        /// </summary>
        internal static string UserName_Exists {
            get {
                return ResourceManager.GetString("UserName_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name is invalid.
        /// </summary>
        internal static string UserName_Invalid {
            get {
                return ResourceManager.GetString("UserName_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username must be less than 50 characters.
        /// </summary>
        internal static string UserName_Length_1_Ignore_to_50_Inclusive {
            get {
                return ResourceManager.GetString("UserName_Length_1_Ignore_to_50_Inclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is required.
        /// </summary>
        internal static string UserName_Length_1_Inclusive_to_50_Ignore {
            get {
                return ResourceManager.GetString("UserName_Length_1_Inclusive_to_50_Ignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username must be between 1 and 50 characters.
        /// </summary>
        internal static string UserName_Length_1_Inclusive_to_50_Inclusive {
            get {
                return ResourceManager.GetString("UserName_Length_1_Inclusive_to_50_Inclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User does not exist.
        /// </summary>
        internal static string UserNotExist {
            get {
                return ResourceManager.GetString("UserNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been locked out due to too many password attempts, please try again later..
        /// </summary>
        internal static string UserTemporarilyLockedOut {
            get {
                return ResourceManager.GetString("UserTemporarilyLockedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid Fields is required.
        /// </summary>
        internal static string ValidFields_Required {
            get {
                return ResourceManager.GetString("ValidFields_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be a number.
        /// </summary>
        internal static string Value_ConvertDecimal {
            get {
                return ResourceManager.GetString("Value_ConvertDecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be zero or greater.
        /// </summary>
        internal static string Value_GTEZero {
            get {
                return ResourceManager.GetString("Value_GTEZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is required.
        /// </summary>
        internal static string Value_Required {
            get {
                return ResourceManager.GetString("Value_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT Rate is required in order to Enable VAT.
        /// </summary>
        internal static string VatRate_Required_For_VATEnabled {
            get {
                return ResourceManager.GetString("VatRate_Required_For_VATEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip/Postal must be at least 1 character.
        /// </summary>
        internal static string ZipPostal_Length_1_Inclusive_to_0_Ignore {
            get {
                return ResourceManager.GetString("ZipPostal_Length_1_Inclusive_to_0_Ignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip/Postal must be between 1 and 200 characters.
        /// </summary>
        internal static string ZipPostal_Length_1_Inclusive_to_200_Inclusive {
            get {
                return ResourceManager.GetString("ZipPostal_Length_1_Inclusive_to_200_Inclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !.
        /// </summary>
        internal static string _ {
            get {
                return ResourceManager.GetString("_", resourceCulture);
            }
        }
    }
}
